//! Router-owned request and fallback identities.
//!
//! IDs stay private to the router→plane hop. They are generated from the operating system CSPRNG
//! and formatted as canonical lowercase UUIDv4 values; callers never parse or trust client input.

/// Typed router-owned identity for one external customer request.
pub(crate) struct LogicalRequestId(String);

impl LogicalRequestId {
    pub(crate) fn fresh() -> Result<Self, ()> {
        fresh_uuid_v4("logical_request").map(Self)
    }

    pub(crate) fn as_str(&self) -> &str {
        &self.0
    }
}

pub(crate) fn fresh_execution_group_id() -> Result<String, ()> {
    fresh_uuid_v4("execution_group")
}

/// Public Anthropic request ID for a router-generated error. This is separate from the private
/// logical/execution identities, but uses the same canonical OS-CSPRNG UUIDv4 representation.
pub(crate) fn fresh_error_request_id() -> Result<String, ()> {
    fresh_uuid_v4("synthetic_error").map(|uuid| format!("req_{}", uuid.replace('-', "")))
}

fn fresh_uuid_v4(purpose: &'static str) -> Result<String, ()> {
    let mut bytes = [0_u8; 16];
    if getrandom::fill(&mut bytes).is_err() {
        // `purpose` comes only from the two fixed call sites above. Neither generated bytes nor OS
        // error details enter the journal.
        elog::error(
            "router-identity",
            format!("router UUIDv4 entropy unavailable purpose={purpose}"),
        );
        return Err(());
    }
    Ok(canonical_uuid_v4(bytes))
}

fn canonical_uuid_v4(mut bytes: [u8; 16]) -> String {
    bytes[6] = (bytes[6] & 0x0f) | 0x40;
    bytes[8] = (bytes[8] & 0x3f) | 0x80;
    format!(
        "{:02x}{:02x}{:02x}{:02x}-{:02x}{:02x}-{:02x}{:02x}-{:02x}{:02x}-{:02x}{:02x}{:02x}{:02x}{:02x}{:02x}",
        bytes[0],
        bytes[1],
        bytes[2],
        bytes[3],
        bytes[4],
        bytes[5],
        bytes[6],
        bytes[7],
        bytes[8],
        bytes[9],
        bytes[10],
        bytes[11],
        bytes[12],
        bytes[13],
        bytes[14],
        bytes[15],
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    fn assert_canonical_uuid_v4(value: &str) {
        let bytes = value.as_bytes();
        assert_eq!(bytes.len(), 36);
        assert_eq!(
            (bytes[8], bytes[13], bytes[18], bytes[23]),
            (b'-', b'-', b'-', b'-')
        );
        assert_eq!(bytes[14], b'4');
        assert!(matches!(bytes[19], b'8' | b'9' | b'a' | b'b'));
        assert!(bytes.iter().enumerate().all(|(index, byte)| {
            matches!(index, 8 | 13 | 18 | 23) || matches!(byte, b'0'..=b'9' | b'a'..=b'f')
        }));
    }

    #[test]
    fn deterministic_formatter_is_canonical_version_four_with_rfc_variant() {
        let value = canonical_uuid_v4([
            0xAB, 0xCD, 0xEF, 0x01, 0x23, 0x45, 0xF6, 0x78, 0x41, 0x23, 0x45, 0x67, 0x89, 0xAB,
            0xCD, 0xEF,
        ]);
        assert_eq!(value, "abcdef01-2345-4678-8123-456789abcdef");
        assert_canonical_uuid_v4(&value);
    }

    #[test]
    fn generated_logical_execution_and_error_ids_are_canonical_and_distinct() {
        let logical = LogicalRequestId::fresh().unwrap();
        let execution = fresh_execution_group_id().unwrap();
        let error = fresh_error_request_id().unwrap();
        assert_canonical_uuid_v4(logical.as_str());
        assert_canonical_uuid_v4(&execution);
        assert_eq!(error.len(), 36);
        assert!(error.starts_with("req_"));
        assert!(error[4..]
            .bytes()
            .all(|byte| byte.is_ascii_digit() || matches!(byte, b'a'..=b'f')));
        assert_ne!(logical.as_str(), execution);
        assert_ne!(logical.as_str().replace('-', ""), error[4..]);
        assert_ne!(execution.replace('-', ""), error[4..]);
    }
}
