#!/usr/bin/env bash

# Canonical object manifest for the retired pricing authority. This file is data: callers source it
# after enabling their own strict shell mode. Keep the order aligned with the explicit topological
# drop groups in docs/ops/PRICING_RETIREMENT.md.

engine_tables=(
  account_funding_head_v2
  account_policy_bindings
  funding_ledger_allocations_v2
  funding_reservation_allocations_v2
  ledger_funding_allocations
  pricing_catalog_heads
  pricing_release_assignment_extensions_v2
  pricing_release_assignments
  pricing_release_head_v2
  pricing_release_recovery_links
  pricing_request_funding_allocations_v2
  pricing_shadow_admission_evaluations
  provider_switch_entries
  provider_switch_head
  reservation_funding_allocations
  funding_buckets
  funding_lots_v2
  funding_reservation_snapshots_v2
  pricing_admission_snapshots
  pricing_release_activations_v2
  pricing_request_snapshots_v2
  account_funding_generations_v2
  account_policy_rules
  pricing_catalog_entries
  pricing_release_policy_rules
  pricing_stage8_evidence_v2
  account_policy_versions
  pricing_release_policy_versions
  pricing_release_versions
  pricing_catalog_versions
  provider_switch_versions
)

commerce_tables=(
  account_policy_reconciliations
  account_policy_rules
  business_invite_policy_bindings
  business_invite_policy_snapshots_v2
  engine_catalog_jobs
  engine_policy_jobs
  engine_switch_jobs
  pricing_funding_normalizations_v2
  pricing_months
  pricing_policy_heads
  pricing_policy_rules
  pricing_policy_rules_v2
  pricing_release_activation_receipts_v2
  pricing_release_assignments_v2
  pricing_release_control_jobs_v2
  pricing_release_orchestrations_v2
  pricing_shadow_policy_jobs_v2
  pricing_stage5_blockers_v2
  pricing_stage5_prepare_acks_v2
  pricing_stage8_capture_artifacts_v2
  pricing_usage_funding_allocations
  product_catalog_heads
  provider_capability_aliases
  provider_capability_head
  provider_switch_entries
  provider_switch_head
  service_account_inventory_v2
  account_policy_bindings
  pricing_policy_documents_v2
  pricing_shadow_rollouts_v2
  pricing_stage8_capture_jobs_v2
  pricing_stage8_evidence_v2
  pricing_usage_attributions
  product_catalog_entries
  account_policy_versions
  pricing_release_plans_v2
  pricing_stage5_runs_v2
  provider_capability_entries
  pricing_policy_versions
  provider_switch_versions
  pricing_policies
  product_catalog_versions
  provider_capability_versions
)

# Keep the Drizzle export names paired with commerce_tables. SQL table-name scanning alone is not
# sufficient: a future reader could import one of these symbols without repeating its SQL name.
commerce_symbols=(
  accountPolicyReconciliations
  accountPolicyRules
  businessInvitePolicyBindings
  businessInvitePolicySnapshotsV2
  engineCatalogJobs
  enginePolicyJobs
  engineSwitchJobs
  pricingFundingNormalizationsV2
  pricingMonths
  pricingPolicyHeads
  pricingPolicyRules
  pricingPolicyRulesV2
  pricingReleaseActivationReceiptsV2
  pricingReleaseAssignmentsV2
  pricingReleaseControlJobsV2
  pricingReleaseOrchestrationsV2
  pricingShadowPolicyJobsV2
  pricingStage5BlockersV2
  pricingStage5PrepareAcksV2
  pricingStage8CaptureArtifactsV2
  pricingUsageFundingAllocations
  productCatalogHeads
  providerCapabilityAliases
  providerCapabilityHead
  providerSwitchEntries
  providerSwitchHead
  serviceAccountInventoryV2
  accountPolicyBindings
  pricingPolicyDocumentsV2
  pricingShadowRolloutsV2
  pricingStage8CaptureJobsV2
  pricingStage8EvidenceV2
  pricingUsageAttributions
  productCatalogEntries
  accountPolicyVersions
  pricingReleasePlansV2
  pricingStage5RunsV2
  providerCapabilityEntries
  pricingPolicyVersions
  providerSwitchVersions
  pricingPolicies
  productCatalogVersions
  providerCapabilityVersions
)

# Minimal live-table survival set for post-contraction evidence. These are not a complete public
# schema inventory: they are the money, queue and reconciliation authorities whose accidental loss
# would make a successful retired-object drop meaningless. New unrelated live tables need not be
# added; replacement/removal of one of these authorities requires an explicit runbook update.
engine_live_tables=(
  engine_schema_migrations
  accounts
  api_keys
  reservations
  settlement_outbox
  ledger
  ledger_consumer_checkpoints
  usage_events
  account_provider_discounts
  pricing_tariff_overrides
)

commerce_live_tables=(
  users
  customer_profiles
  engine_accounts
  engine_pricing_jobs
  engine_credits
  engine_adjustments
  customer_provider_discounts
  pricing_credit_accruals
  pricing_usage_events
  pricing_usage_cursors
  pricing_usage_topups
  payments
  referral_attributions
  webhook_events
)

engine_retired_functions=(
  'assert_active_funding_account_v2(text)'
  'assert_funding_generation_v2(text, bigint)'
  'assert_funding_reservation_snapshot_v2(text)'
  'assert_normalized_reservation_funding_v2(text)'
  'assert_pricing_release_assignment_extension_pair_v2()'
  'assert_pricing_request_funding_v2(text)'
  'assert_strict_funding_account(text)'
  'assert_strict_reservation(text)'
  'enforce_account_funding_head_step_v2()'
  'enforce_active_funding_v2_from_account()'
  'enforce_active_funding_v2_from_head()'
  'enforce_funding_generation_v2_from_generation()'
  'enforce_funding_generation_v2_from_lot()'
  'enforce_funding_ledger_v2_account()'
  'enforce_funding_reservation_allocation_v2_update()'
  'enforce_funding_reservation_snapshot_v2_account()'
  'enforce_funding_reservation_v2_from_allocation()'
  'enforce_funding_reservation_v2_from_head()'
  'enforce_funding_reservation_v2_from_reservation()'
  'enforce_funding_reservation_v2_from_snapshot()'
  'enforce_ledger_funding_allocation_account()'
  'enforce_pricing_release_activation_v2()'
  'enforce_pricing_release_assignment_extension_v2()'
  'enforce_pricing_release_head_audit_v2()'
  'enforce_pricing_release_head_step_v2()'
  'enforce_pricing_release_recovery_kinds_v2()'
  'enforce_pricing_release_rule_owner_v2()'
  'enforce_pricing_request_funding_v2_from_allocation()'
  'enforce_pricing_request_funding_v2_from_reservation()'
  'enforce_pricing_request_funding_v2_from_snapshot()'
  'enforce_pricing_request_v2_account()'
  'enforce_pricing_shadow_admission_rule_identity()'
  'enforce_pricing_snapshot_reservation_account()'
  'enforce_release_v2_lineage()'
  'enforce_service_meter_only_policy_rule()'
  'enforce_strict_binding_cutover()'
  'enforce_strict_binding_runtime_floor()'
  'enforce_strict_binding_state()'
  'enforce_strict_funding_account_from_account()'
  'enforce_strict_funding_account_from_bucket()'
  'enforce_strict_key_policy_ack()'
  'enforce_strict_reservation_from_allocation()'
  'enforce_strict_reservation_from_reservation()'
  'reject_funding_reservation_snapshot_v2_update()'
  'reject_immutable_pricing_release_v2_mutation()'
  'reject_pricing_request_v2_update()'
  'reject_pricing_shadow_admission_evaluation_update()'
  'reject_pricing_snapshot_update()'
)

engine_live_functions=(
  'enforce_account_settlement_floor_fence()'
  'enforce_priced_terminal_collection_fence()'
  'enforce_pricing_tariff_override_version()'
  'reject_pricing_tariff_override_mutation()'
)

commerce_retired_functions=(
  'enforce_pricing_policy_rule_v2_owner()'
  'guard_pricing_release_assignment_v2()'
  'guard_pricing_release_plan_v2()'
  'guard_pricing_stage5_run_v2()'
  'notify_pricing_control_job()'
)

commerce_live_functions=(
  'enforce_blog_draft_identity()'
  'enforce_blog_first_publication()'
)
