//! Authenticated per-account model-rate projection for the stateless unified router.
//!
//! The provider runtimes remain the pricing authority: they authenticate the customer credential,
//! resolve the same legacy scalar or strict account policy used by admission, and combine it with
//! the audited provider tariffs from `metering`. The response contains only opaque candidate IDs
//! and integer nanoUSD rate strings. Account, credential, policy and rule identities never leave
//! the fixed runtime and nothing in this read-only path mutates money.

use axum::extract::rejection::JsonRejection;
use axum::extract::{ConnectInfo, State};
use axum::http::{HeaderMap, StatusCode};
use axum::response::{IntoResponse, Response};
use axum::Json;
use forward::{
    authed, resolve_client_key, resolve_pricing, AppState, PricingResolution,
    PricingResolutionRequest, RuntimePricingManifest,
};
use metering::{
    AnthropicAdmissionModifiers, AnthropicInferenceGeo, AnthropicSpeed, CodexModelSpec,
    CodexPrices, GeminiPrices,
};
use serde::{Deserialize, Serialize};
use serde_json::json;
use std::collections::BTreeSet;
use std::net::SocketAddr;

const SCHEMA_VERSION: u64 = 1;
const UNIT: &str = "nano_usd_per_million_tokens";
const MAX_CANDIDATES: usize = 256;
const MAX_ID_BYTES: usize = 256;
const TOKENS_PER_MILLION: i128 = 1_000_000;

#[derive(Debug, Deserialize)]
#[serde(deny_unknown_fields)]
pub(crate) struct PricingRequest {
    schema_version: u64,
    candidates: Vec<Candidate>,
}

#[derive(Clone, Debug, Deserialize)]
#[serde(deny_unknown_fields)]
struct Candidate {
    /// Opaque correlation identity generated by the router from its public catalog entry.
    id: String,
    provider_id: String,
    /// Provider-native model ID from the authenticated plane catalog.
    model_id: String,
}

#[derive(Clone, Debug, Serialize)]
struct RateCard {
    input: String,
    output: String,
    cache_read: String,
    /// Default cache-write class consumed by OpenCode. Anthropic maps this to the normal 5m write.
    cache_write: String,
    /// Anthropic's separately priced 1h write, retained for clients that can distinguish it.
    #[serde(skip_serializing_if = "Option::is_none")]
    cache_write_1h: Option<String>,
}

#[derive(Clone, Debug, Serialize)]
struct ContextTier {
    threshold_tokens: u64,
    standard: RateCard,
    #[serde(skip_serializing_if = "Option::is_none")]
    priority: Option<RateCard>,
}

#[derive(Clone, Debug, Serialize)]
struct PricingEntry {
    id: String,
    standard: RateCard,
    #[serde(skip_serializing_if = "Option::is_none")]
    priority: Option<RateCard>,
    #[serde(skip_serializing_if = "Option::is_none")]
    long_context: Option<ContextTier>,
}

#[derive(Clone, Debug)]
struct BasePricing {
    canonical_model_id: String,
    standard: RawRateCard,
    priority: Option<RawRateCard>,
    long_context: Option<RawContextTier>,
}

#[derive(Clone, Copy, Debug)]
struct RawRateCard {
    input: i128,
    output: i128,
    cache_read: i128,
    cache_write: i128,
    cache_write_1h: Option<i128>,
}

#[derive(Clone, Copy, Debug)]
struct RawContextTier {
    threshold_tokens: u64,
    standard: RawRateCard,
    priority: Option<RawRateCard>,
}

fn valid_id(value: &str) -> bool {
    !value.is_empty()
        && value.len() <= MAX_ID_BYTES
        && value.trim() == value
        && !value.bytes().any(|byte| byte.is_ascii_control())
}

fn validate(request: &PricingRequest) -> bool {
    if request.schema_version != SCHEMA_VERSION
        || request.candidates.is_empty()
        || request.candidates.len() > MAX_CANDIDATES
    {
        return false;
    }
    let mut ids = BTreeSet::new();
    request.candidates.iter().all(|candidate| {
        valid_id(&candidate.id)
            && valid_id(&candidate.model_id)
            && matches!(
                candidate.provider_id.as_str(),
                "anthropic" | "openai" | "google" | "kimi"
            )
            && ids.insert(candidate.id.as_str())
    })
}

fn error(status: StatusCode, code: &'static str, message: &'static str) -> Response {
    (
        status,
        Json(json!({"error": {"code": code, "message": message}})),
    )
        .into_response()
}

fn response(mode: &'static str, entries: Vec<PricingEntry>) -> Response {
    (
        StatusCode::OK,
        Json(json!({
            "schema_version": SCHEMA_VERSION,
            "unit": UNIT,
            "mode": mode,
            "entries": entries,
        })),
    )
        .into_response()
}

fn scaled_rate(rate_per_token: i128, multiplier_bp: i64) -> String {
    metering::apply_multiplier(
        rate_per_token.saturating_mul(TOKENS_PER_MILLION),
        multiplier_bp,
    )
    .max(0)
    .to_string()
}

fn rate_card(raw: RawRateCard, multiplier_bp: i64) -> RateCard {
    RateCard {
        input: scaled_rate(raw.input, multiplier_bp),
        output: scaled_rate(raw.output, multiplier_bp),
        cache_read: scaled_rate(raw.cache_read, multiplier_bp),
        cache_write: scaled_rate(raw.cache_write, multiplier_bp),
        cache_write_1h: raw
            .cache_write_1h
            .map(|rate| scaled_rate(rate, multiplier_bp)),
    }
}

fn apply_basis_points(rate: i128, basis_points: i64) -> i128 {
    metering::apply_multiplier(rate, basis_points)
}

fn anthropic_pricing(model_id: &str, now: i64) -> BasePricing {
    // Route through the same hot tariff book the engine charges with, so a router quote never
    // diverges from a reserve/settlement of the same turn. A model no branch recognizes has no
    // family and keeps the conservative compiled fallback.
    let prices = match metering::anthropic_matched_tariff_at(model_id, now, false) {
        Some((family, compiled)) => forward::tariff_book::reserve_base(
            &forward::tariff_book::snapshot(),
            family,
            now,
            compiled,
            forward::tariff_book::as_anthropic,
        )
        .prices,
        None => metering::model_prices_at(model_id, now),
    };
    let canonical_model_id = metering::anthropic_tariff_capability_at(
        model_id,
        now,
        AnthropicAdmissionModifiers {
            speed: AnthropicSpeed::Standard,
            inference_geo: AnthropicInferenceGeo::Global,
        },
    )
    .map(|identity| identity.canonical_model_id.to_owned())
    .unwrap_or_else(|_| model_id.to_owned());
    BasePricing {
        canonical_model_id,
        standard: RawRateCard {
            input: prices.input,
            output: prices.output,
            cache_read: prices.cache_read,
            cache_write: prices.cache_write_5m,
            cache_write_1h: Some(prices.cache_write_1h),
        },
        priority: None,
        long_context: None,
    }
}

fn codex_rate_card(prices: CodexPrices, input_bp: i64, output_bp: i64, fast: bool) -> RawRateCard {
    let fast_bp = if fast {
        prices.api_fast_multiplier_basis_points
    } else {
        10_000
    };
    RawRateCard {
        input: apply_basis_points(apply_basis_points(prices.input, input_bp), fast_bp),
        output: apply_basis_points(apply_basis_points(prices.output, output_bp), fast_bp),
        cache_read: apply_basis_points(apply_basis_points(prices.cached_input, input_bp), fast_bp),
        cache_write: apply_basis_points(
            apply_basis_points(prices.cache_write_input, input_bp),
            fast_bp,
        ),
        cache_write_1h: None,
    }
}

fn codex_pricing(spec: &CodexModelSpec, now: i64) -> BasePricing {
    let prices = match metering::codex_matched_tariff_at(spec.id, now) {
        Some((family, compiled)) => forward::tariff_book::reserve_base(
            &forward::tariff_book::snapshot(),
            family,
            now,
            compiled,
            forward::tariff_book::as_codex,
        )
        .prices,
        None => spec.prices,
    };
    let standard = codex_rate_card(prices, 10_000, 10_000, false);
    let priority = spec
        .subscription_fast_multiplier_basis_points
        .map(|_| codex_rate_card(prices, 10_000, 10_000, true));
    let long_context = Some(RawContextTier {
        threshold_tokens: prices.long_context_threshold,
        standard: codex_rate_card(
            prices,
            prices.long_input_basis_points,
            prices.long_output_basis_points,
            false,
        ),
        priority: spec.subscription_fast_multiplier_basis_points.map(|_| {
            codex_rate_card(
                prices,
                prices.long_input_basis_points,
                prices.long_output_basis_points,
                true,
            )
        }),
    });
    BasePricing {
        canonical_model_id: spec.upstream.to_owned(),
        standard,
        priority,
        long_context,
    }
}

fn gemini_rate_card(prices: GeminiPrices, long: bool) -> RawRateCard {
    RawRateCard {
        input: if long {
            prices.long_input
        } else {
            prices.input
        },
        output: if long {
            prices.long_output
        } else {
            prices.output
        },
        cache_read: if long {
            prices.long_cached_input
        } else {
            prices.cached_input
        },
        // Gemini cached-token usage is a read discount; no explicit cache-write token class is
        // reported to OpenCode, so inventing a write charge here would double count input.
        cache_write: 0,
        cache_write_1h: None,
    }
}

/// Rate card of a KIMI subscription alias.
///
/// The four published legs map one to one: a cache hit is the read rate, a cache miss is plain
/// input, and KIMI publishes no separate write rate — a write *is* a miss — so `cache_write`
/// equals `input` rather than the zero a "no write class" reading would suggest. Reasoning tokens
/// are a subset of output at the output rate and never form a fifth leg. There is no long-context
/// tier: the 1M window is a different alias, not a different price, so quoting a threshold here
/// would invent a step that settlement does not charge.
fn kimi_pricing(canonical_model_id: &str, prices: metering::KimiPrices) -> BasePricing {
    BasePricing {
        canonical_model_id: canonical_model_id.to_owned(),
        standard: RawRateCard {
            input: prices.input,
            output: prices.output,
            cache_read: prices.cached_input,
            cache_write: prices.cache_write,
            cache_write_1h: None,
        },
        priority: None,
        long_context: None,
    }
}

fn gemini_pricing(model_id: &str, prices: GeminiPrices) -> BasePricing {
    let long_context = (prices.long_context_threshold != u64::MAX).then(|| RawContextTier {
        threshold_tokens: prices.long_context_threshold,
        standard: gemini_rate_card(prices, true),
        priority: None,
    });
    BasePricing {
        canonical_model_id: model_id.to_owned(),
        standard: gemini_rate_card(prices, false),
        priority: None,
        long_context,
    }
}

/// Rate card of an Images API model.
///
/// The public card carries the three legs that share its token classes with a text model: text
/// input, cached text input and generated output tokens. GPT Image 2 also meters *image* input
/// tokens on edits at their own audited rate; the closed OpenAI-compatible card has no field for
/// that class, so it is documented in `docs/commerce/PRICING.md` rather than folded into a leg
/// that would then misprice plain generation. This mirrors how the Gemini image model publishes
/// one card for a model whose output tokens are images.
fn openai_image_pricing(tariff: &metering::OpenAiImageTariffIdentity, now: i64) -> BasePricing {
    let prices = forward::tariff_book::reserve_base(
        &forward::tariff_book::snapshot(),
        metering::openai_image_tariff_family(),
        now,
        tariff.prices,
        forward::tariff_book::as_openai_image,
    )
    .prices;
    BasePricing {
        canonical_model_id: tariff.canonical_model_id.to_owned(),
        standard: RawRateCard {
            input: prices.fresh_text_input,
            output: prices.image_output,
            cache_read: prices.cached_text_input,
            // The image wire reports no cache-write token class; charging one would double count.
            cache_write: 0,
            cache_write_1h: None,
        },
        priority: None,
        long_context: None,
    }
}

fn base_pricing(candidate: &Candidate, now: i64) -> Option<BasePricing> {
    match candidate.provider_id.as_str() {
        "anthropic" => Some(anthropic_pricing(&candidate.model_id, now)),
        "openai" => metering::codex_catalog_at(now)
            .into_iter()
            .find(|model| model.id == candidate.model_id)
            .map(|model| codex_pricing(&model, now))
            .or_else(|| {
                metering::openai_image_tariff(&candidate.model_id)
                    .ok()
                    .map(|tariff| openai_image_pricing(&tariff, now))
            }),
        "google" => metering::gemini_matched_tariff_at(&candidate.model_id, now).map(
            |(family, compiled)| {
                let prices = forward::tariff_book::reserve_base(
                    &forward::tariff_book::snapshot(),
                    family,
                    now,
                    compiled,
                    forward::tariff_book::as_gemini,
                )
                .prices;
                gemini_pricing(&candidate.model_id, prices)
            },
        ),
        // Only a published subscription alias is quotable. `kimi_matched_tariff_at` also answers
        // for the official Open Platform ids, but those are tariff keys we never accept on the
        // wire, so quoting one would advertise a model the plane refuses.
        "kimi" => metering::kimi_resolve_subscription_model(&candidate.model_id).and_then(
            |resolved| {
                let (family, compiled) = metering::kimi_matched_tariff_at(&candidate.model_id, now)?;
                let prices = forward::tariff_book::reserve_base(
                    &forward::tariff_book::snapshot(),
                    family,
                    now,
                    compiled,
                    forward::tariff_book::as_kimi,
                )
                .prices;
                Some(kimi_pricing(resolved.official_model, prices))
            },
        ),
        _ => None,
    }
}

fn priced_entry(id: String, base: BasePricing, multiplier_bp: i64) -> PricingEntry {
    PricingEntry {
        id,
        standard: rate_card(base.standard, multiplier_bp),
        priority: base.priority.map(|raw| rate_card(raw, multiplier_bp)),
        long_context: base.long_context.map(|tier| ContextTier {
            threshold_tokens: tier.threshold_tokens,
            standard: rate_card(tier.standard, multiplier_bp),
            priority: tier.priority.map(|raw| rate_card(raw, multiplier_bp)),
        }),
    }
}

/// Return personalized model token rates without reservation, settlement or any other money write.
pub(crate) async fn pricing(
    State(app): State<AppState>,
    ConnectInfo(peer): ConnectInfo<SocketAddr>,
    headers: HeaderMap,
    payload: Result<Json<PricingRequest>, JsonRejection>,
) -> Response {
    let Ok(Json(request)) = payload else {
        return error(
            StatusCode::BAD_REQUEST,
            "invalid_request",
            "Invalid catalog pricing request.",
        );
    };
    if !validate(&request) {
        return error(
            StatusCode::BAD_REQUEST,
            "invalid_request",
            "Invalid catalog pricing request.",
        );
    }

    let now = pool::now();
    let bases: Vec<_> = request
        .candidates
        .iter()
        .filter_map(|candidate| base_pricing(candidate, now).map(|base| (candidate, base)))
        .collect();

    if authed(&app, &headers, &peer) {
        return response(
            "admin",
            bases
                .into_iter()
                .map(|(candidate, base)| priced_entry(candidate.id.clone(), base, 10_000))
                .collect(),
        );
    }

    let Some(billing) = app.billing.as_ref() else {
        return error(
            StatusCode::UNAUTHORIZED,
            "unauthorized",
            "Invalid API credential.",
        );
    };
    let auth = match resolve_client_key(billing, &headers).await {
        Ok(Some((_, auth))) if auth.active_at(now) => auth,
        Ok(Some(_)) => {
            return error(
                StatusCode::UNAUTHORIZED,
                "unauthorized",
                "Invalid API credential.",
            )
        }
        Ok(None) => {
            return error(
                StatusCode::UNAUTHORIZED,
                "unauthorized",
                "Invalid API credential.",
            )
        }
        Err(_) => {
            return error(
                StatusCode::SERVICE_UNAVAILABLE,
                "pricing_unavailable",
                "Catalog pricing is temporarily unavailable.",
            )
        }
    };

    if !auth.strict_policy() {
        return response(
            "legacy",
            bases
                .into_iter()
                .map(|(candidate, base)| priced_entry(candidate.id.clone(), base, auth.mult_bp))
                .collect(),
        );
    }

    let bundle = match billing.pricing_read_bundle(&auth.account_id).await {
        Ok(bundle) => bundle,
        Err(_) => {
            return error(
                StatusCode::SERVICE_UNAVAILABLE,
                "pricing_unavailable",
                "Catalog pricing is temporarily unavailable.",
            )
        }
    };
    let manifest = RuntimePricingManifest::from_evidence(&app.pricing_manifest);
    let entries = bases
        .into_iter()
        .filter_map(|(candidate, base)| {
            // Strict Gemini admission is intentionally unavailable today; the catalog must not
            // advertise a personalized rate for a model that this key cannot execute. KIMI is in
            // the same position for a different reason: its gateway refuses a strict key outright
            // (`kimi_strict_pricing_unavailable`) because the release catalog has no `kimi`
            // provider yet, so a quote here would be an offer we cannot honour.
            if candidate.provider_id == "google" || candidate.provider_id == "kimi" {
                return None;
            }
            match resolve_pricing(
                &bundle,
                &PricingResolutionRequest {
                    account_id: auth.account_id.clone(),
                    provider_id: candidate.provider_id.clone(),
                    requested_model_id: candidate.model_id.clone(),
                    canonical_model_id: base.canonical_model_id.clone(),
                },
                &manifest,
            ) {
                PricingResolution::Resolved(resolved) => Some(priced_entry(
                    candidate.id.clone(),
                    base,
                    resolved.rule.payable_multiplier_bp,
                )),
                PricingResolution::Rejected(_) => None,
            }
        })
        .collect();
    response("strict", entries)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn integer_rate_projection_applies_account_multiplier_once() {
        let card = rate_card(
            RawRateCard {
                input: 5_000,
                output: 30_000,
                cache_read: 500,
                cache_write: 6_250,
                cache_write_1h: None,
            },
            5_000,
        );
        assert_eq!(card.input, "2500000000");
        assert_eq!(card.output, "15000000000");
        assert_eq!(card.cache_read, "250000000");
        assert_eq!(card.cache_write, "3125000000");
    }

    #[test]
    fn fast_and_long_context_rates_preserve_modifier_order() {
        let spec = metering::codex_catalog_at(1_785_369_601)
            .into_iter()
            .find(|model| model.id == "gpt-5.6-sol")
            .unwrap();
        let pricing = codex_pricing(&spec, 1_785_369_601);
        let priority = pricing.priority.unwrap();
        assert_eq!(priority.input, 10_000);
        assert_eq!(priority.output, 60_000);
        let long = pricing.long_context.unwrap();
        assert_eq!(long.threshold_tokens, 272_000);
        assert_eq!(long.standard.input, 10_000);
        assert_eq!(long.standard.output, 45_000);
        assert_eq!(long.priority.unwrap().output, 90_000);
    }

    /// The router drops any catalog entry it cannot price, so an image model that this producer
    /// does not resolve is invisible in `/v1/models` no matter what the plane publishes.
    #[test]
    fn image_models_resolve_a_key_scoped_rate_card() {
        for model_id in ["gpt-image-2", "gpt-image-2-2026-04-21"] {
            let candidate = Candidate {
                id: format!("openai/{model_id}"),
                provider_id: "openai".to_owned(),
                model_id: model_id.to_owned(),
            };
            let base = base_pricing(&candidate, 0).expect("image model is priced");
            // Both public ids settle against the one immutable snapshot identity.
            assert_eq!(base.canonical_model_id, "gpt-image-2-2026-04-21");
            assert!(base.priority.is_none() && base.long_context.is_none());
            let card = rate_card(base.standard, 10_000);
            assert_eq!(card.input, "5000000000");
            assert_eq!(card.output, "30000000000");
            assert_eq!(card.cache_read, "1250000000");
            assert_eq!(card.cache_write, "0");
        }

        let unknown = Candidate {
            id: "openai/gpt-image-1".to_owned(),
            provider_id: "openai".to_owned(),
            model_id: "gpt-image-1".to_owned(),
        };
        assert!(base_pricing(&unknown, 0).is_none());
    }

    /// Only a subscription alias is quotable, and every leg is the audited KIMI card: a cache
    /// write is a miss (never zero, as it would be for Gemini), and there is no long-context step
    /// because the 1M window is a different alias rather than a different price.
    #[test]
    fn kimi_quotes_only_published_aliases_at_the_audited_card() {
        const NOW: i64 = 1_788_220_800;
        for alias in [
            "kimi-for-coding",
            "kimi-for-coding-highspeed",
            "k3",
            "k3[1m]",
            "k3-256k",
        ] {
            let candidate = Candidate {
                id: format!("kimi/{alias}"),
                provider_id: "kimi".to_owned(),
                model_id: alias.to_owned(),
            };
            let base = base_pricing(&candidate, NOW)
                .unwrap_or_else(|| panic!("{alias} must resolve a rate card"));
            let expected = metering::kimi_prices_for_served_model(alias, NOW).expect("priced");
            assert_eq!(base.standard.input, expected.input, "{alias}");
            assert_eq!(base.standard.output, expected.output, "{alias}");
            assert_eq!(base.standard.cache_read, expected.cached_input, "{alias}");
            assert_eq!(base.standard.cache_write, expected.input, "{alias}");
            assert!(base.long_context.is_none() && base.priority.is_none(), "{alias}");
        }

        // The official Open Platform ids are tariff keys, not wire ids: `kimi_matched_tariff_at`
        // answers for them, so quoting one would advertise a model the gateway refuses.
        for official in ["kimi-k3", "kimi-k2.6", "kimi-k2.7-code"] {
            let candidate = Candidate {
                id: format!("kimi/{official}"),
                provider_id: "kimi".to_owned(),
                model_id: official.to_owned(),
            };
            assert!(base_pricing(&candidate, NOW).is_none(), "{official}");
        }
    }

    #[test]
    fn request_validation_is_bounded_and_provider_fixed() {        let valid = PricingRequest {
            schema_version: 1,
            candidates: vec![Candidate {
                id: "openai/gpt-5.6".to_owned(),
                provider_id: "openai".to_owned(),
                model_id: "gpt-5.6".to_owned(),
            }],
        };
        assert!(validate(&valid));
        let mut invalid = valid;
        invalid.candidates[0].provider_id = "client-provider".to_owned();
        assert!(!validate(&invalid));
    }
}
