//! Authenticated per-account model-rate projection for the stateless unified router.
//!
//! The provider runtimes remain the pricing authority: they authenticate the customer credential,
//! resolve the same legacy scalar or strict account policy used by admission, and combine it with
//! the audited provider tariffs from `metering`. The response contains only opaque candidate IDs
//! and integer nanoUSD rate strings. Account, credential, policy and rule identities never leave
//! the fixed runtime and nothing in this read-only path mutates money.

use axum::extract::rejection::JsonRejection;
use axum::extract::{ConnectInfo, State};
use axum::http::{HeaderMap, StatusCode};
use axum::response::{IntoResponse, Response};
use axum::Json;
use forward::{
    authed, resolve_client_key, resolve_pricing, AppState, PricingResolution,
    PricingResolutionRequest, RuntimePricingManifest,
};
use metering::{
    AnthropicAdmissionModifiers, AnthropicInferenceGeo, AnthropicSpeed, CodexModelSpec,
    CodexPrices, GeminiPrices,
};
use serde::{Deserialize, Serialize};
use serde_json::json;
use std::collections::BTreeSet;
use std::net::SocketAddr;

const SCHEMA_VERSION: u64 = 1;
const UNIT: &str = "nano_usd_per_million_tokens";
const MAX_CANDIDATES: usize = 256;
const MAX_ID_BYTES: usize = 256;
const TOKENS_PER_MILLION: i128 = 1_000_000;

#[derive(Debug, Deserialize)]
#[serde(deny_unknown_fields)]
pub(crate) struct PricingRequest {
    schema_version: u64,
    candidates: Vec<Candidate>,
}

#[derive(Clone, Debug, Deserialize)]
#[serde(deny_unknown_fields)]
struct Candidate {
    /// Opaque correlation identity generated by the router from its public catalog entry.
    id: String,
    provider_id: String,
    /// Provider-native model ID from the authenticated plane catalog.
    model_id: String,
}

#[derive(Clone, Debug, Serialize)]
struct RateCard {
    input: String,
    output: String,
    cache_read: String,
    /// Default cache-write class consumed by OpenCode. Anthropic maps this to the normal 5m write.
    cache_write: String,
    /// Anthropic's separately priced 1h write, retained for clients that can distinguish it.
    #[serde(skip_serializing_if = "Option::is_none")]
    cache_write_1h: Option<String>,
}

#[derive(Clone, Debug, Serialize)]
struct ContextTier {
    threshold_tokens: u64,
    standard: RateCard,
    #[serde(skip_serializing_if = "Option::is_none")]
    priority: Option<RateCard>,
}

#[derive(Clone, Debug, Serialize)]
struct PricingEntry {
    id: String,
    standard: RateCard,
    #[serde(skip_serializing_if = "Option::is_none")]
    priority: Option<RateCard>,
    #[serde(skip_serializing_if = "Option::is_none")]
    long_context: Option<ContextTier>,
}

#[derive(Clone, Debug)]
struct BasePricing {
    canonical_model_id: String,
    standard: RawRateCard,
    priority: Option<RawRateCard>,
    long_context: Option<RawContextTier>,
}

#[derive(Clone, Copy, Debug)]
struct RawRateCard {
    input: i128,
    output: i128,
    cache_read: i128,
    cache_write: i128,
    cache_write_1h: Option<i128>,
}

#[derive(Clone, Copy, Debug)]
struct RawContextTier {
    threshold_tokens: u64,
    standard: RawRateCard,
    priority: Option<RawRateCard>,
}

fn valid_id(value: &str) -> bool {
    !value.is_empty()
        && value.len() <= MAX_ID_BYTES
        && value.trim() == value
        && !value.bytes().any(|byte| byte.is_ascii_control())
}

fn validate(request: &PricingRequest) -> bool {
    if request.schema_version != SCHEMA_VERSION
        || request.candidates.is_empty()
        || request.candidates.len() > MAX_CANDIDATES
    {
        return false;
    }
    let mut ids = BTreeSet::new();
    request.candidates.iter().all(|candidate| {
        valid_id(&candidate.id)
            && valid_id(&candidate.model_id)
            && matches!(
                candidate.provider_id.as_str(),
                "anthropic" | "openai" | "google"
            )
            && ids.insert(candidate.id.as_str())
    })
}

fn error(status: StatusCode, code: &'static str, message: &'static str) -> Response {
    (
        status,
        Json(json!({"error": {"code": code, "message": message}})),
    )
        .into_response()
}

fn response(mode: &'static str, entries: Vec<PricingEntry>) -> Response {
    (
        StatusCode::OK,
        Json(json!({
            "schema_version": SCHEMA_VERSION,
            "unit": UNIT,
            "mode": mode,
            "entries": entries,
        })),
    )
        .into_response()
}

fn scaled_rate(rate_per_token: i128, multiplier_bp: i64) -> String {
    metering::apply_multiplier(
        rate_per_token.saturating_mul(TOKENS_PER_MILLION),
        multiplier_bp,
    )
    .max(0)
    .to_string()
}

fn rate_card(raw: RawRateCard, multiplier_bp: i64) -> RateCard {
    RateCard {
        input: scaled_rate(raw.input, multiplier_bp),
        output: scaled_rate(raw.output, multiplier_bp),
        cache_read: scaled_rate(raw.cache_read, multiplier_bp),
        cache_write: scaled_rate(raw.cache_write, multiplier_bp),
        cache_write_1h: raw
            .cache_write_1h
            .map(|rate| scaled_rate(rate, multiplier_bp)),
    }
}

fn apply_basis_points(rate: i128, basis_points: i64) -> i128 {
    metering::apply_multiplier(rate, basis_points)
}

fn anthropic_pricing(model_id: &str, now: i64) -> BasePricing {
    let prices = metering::model_prices_at(model_id, now);
    let canonical_model_id = metering::anthropic_tariff_capability_at(
        model_id,
        now,
        AnthropicAdmissionModifiers {
            speed: AnthropicSpeed::Standard,
            inference_geo: AnthropicInferenceGeo::Global,
        },
    )
    .map(|identity| identity.canonical_model_id.to_owned())
    .unwrap_or_else(|_| model_id.to_owned());
    BasePricing {
        canonical_model_id,
        standard: RawRateCard {
            input: prices.input,
            output: prices.output,
            cache_read: prices.cache_read,
            cache_write: prices.cache_write_5m,
            cache_write_1h: Some(prices.cache_write_1h),
        },
        priority: None,
        long_context: None,
    }
}

fn codex_rate_card(prices: CodexPrices, input_bp: i64, output_bp: i64, fast: bool) -> RawRateCard {
    let fast_bp = if fast {
        prices.api_fast_multiplier_basis_points
    } else {
        10_000
    };
    RawRateCard {
        input: apply_basis_points(apply_basis_points(prices.input, input_bp), fast_bp),
        output: apply_basis_points(apply_basis_points(prices.output, output_bp), fast_bp),
        cache_read: apply_basis_points(apply_basis_points(prices.cached_input, input_bp), fast_bp),
        cache_write: apply_basis_points(
            apply_basis_points(prices.cache_write_input, input_bp),
            fast_bp,
        ),
        cache_write_1h: None,
    }
}

fn codex_pricing(spec: &CodexModelSpec) -> BasePricing {
    let prices = spec.prices;
    let standard = codex_rate_card(prices, 10_000, 10_000, false);
    let priority = spec
        .subscription_fast_multiplier_basis_points
        .map(|_| codex_rate_card(prices, 10_000, 10_000, true));
    let long_context = Some(RawContextTier {
        threshold_tokens: prices.long_context_threshold,
        standard: codex_rate_card(
            prices,
            prices.long_input_basis_points,
            prices.long_output_basis_points,
            false,
        ),
        priority: spec.subscription_fast_multiplier_basis_points.map(|_| {
            codex_rate_card(
                prices,
                prices.long_input_basis_points,
                prices.long_output_basis_points,
                true,
            )
        }),
    });
    BasePricing {
        canonical_model_id: spec.upstream.to_owned(),
        standard,
        priority,
        long_context,
    }
}

fn gemini_rate_card(prices: GeminiPrices, long: bool) -> RawRateCard {
    RawRateCard {
        input: if long {
            prices.long_input
        } else {
            prices.input
        },
        output: if long {
            prices.long_output
        } else {
            prices.output
        },
        cache_read: if long {
            prices.long_cached_input
        } else {
            prices.cached_input
        },
        // Gemini cached-token usage is a read discount; no explicit cache-write token class is
        // reported to OpenCode, so inventing a write charge here would double count input.
        cache_write: 0,
        cache_write_1h: None,
    }
}

fn gemini_pricing(model_id: &str, prices: GeminiPrices) -> BasePricing {
    let long_context = (prices.long_context_threshold != u64::MAX).then(|| RawContextTier {
        threshold_tokens: prices.long_context_threshold,
        standard: gemini_rate_card(prices, true),
        priority: None,
    });
    BasePricing {
        canonical_model_id: model_id.to_owned(),
        standard: gemini_rate_card(prices, false),
        priority: None,
        long_context,
    }
}

fn base_pricing(candidate: &Candidate, now: i64) -> Option<BasePricing> {
    match candidate.provider_id.as_str() {
        "anthropic" => Some(anthropic_pricing(&candidate.model_id, now)),
        "openai" => metering::codex_catalog_at(now)
            .into_iter()
            .find(|model| model.id == candidate.model_id)
            .map(|model| codex_pricing(&model)),
        "google" => metering::gemini_prices_at(&candidate.model_id, now)
            .map(|prices| gemini_pricing(&candidate.model_id, prices)),
        _ => None,
    }
}

fn priced_entry(id: String, base: BasePricing, multiplier_bp: i64) -> PricingEntry {
    PricingEntry {
        id,
        standard: rate_card(base.standard, multiplier_bp),
        priority: base.priority.map(|raw| rate_card(raw, multiplier_bp)),
        long_context: base.long_context.map(|tier| ContextTier {
            threshold_tokens: tier.threshold_tokens,
            standard: rate_card(tier.standard, multiplier_bp),
            priority: tier.priority.map(|raw| rate_card(raw, multiplier_bp)),
        }),
    }
}

/// Return personalized model token rates without reservation, settlement or any other money write.
pub(crate) async fn pricing(
    State(app): State<AppState>,
    ConnectInfo(peer): ConnectInfo<SocketAddr>,
    headers: HeaderMap,
    payload: Result<Json<PricingRequest>, JsonRejection>,
) -> Response {
    let Ok(Json(request)) = payload else {
        return error(
            StatusCode::BAD_REQUEST,
            "invalid_request",
            "Invalid catalog pricing request.",
        );
    };
    if !validate(&request) {
        return error(
            StatusCode::BAD_REQUEST,
            "invalid_request",
            "Invalid catalog pricing request.",
        );
    }

    let now = pool::now();
    let bases: Vec<_> = request
        .candidates
        .iter()
        .filter_map(|candidate| base_pricing(candidate, now).map(|base| (candidate, base)))
        .collect();

    if authed(&app, &headers, &peer) {
        return response(
            "admin",
            bases
                .into_iter()
                .map(|(candidate, base)| priced_entry(candidate.id.clone(), base, 10_000))
                .collect(),
        );
    }

    let Some(billing) = app.billing.as_ref() else {
        return error(
            StatusCode::UNAUTHORIZED,
            "unauthorized",
            "Invalid API credential.",
        );
    };
    let auth = match resolve_client_key(billing, &headers).await {
        Ok(Some((_, auth))) if auth.active_at(now) => auth,
        Ok(Some(_)) => {
            return error(
                StatusCode::UNAUTHORIZED,
                "unauthorized",
                "Invalid API credential.",
            )
        }
        Ok(None) => {
            return error(
                StatusCode::UNAUTHORIZED,
                "unauthorized",
                "Invalid API credential.",
            )
        }
        Err(_) => {
            return error(
                StatusCode::SERVICE_UNAVAILABLE,
                "pricing_unavailable",
                "Catalog pricing is temporarily unavailable.",
            )
        }
    };

    if !auth.strict_policy() {
        return response(
            "legacy",
            bases
                .into_iter()
                .map(|(candidate, base)| priced_entry(candidate.id.clone(), base, auth.mult_bp))
                .collect(),
        );
    }

    let bundle = match billing.pricing_read_bundle(&auth.account_id).await {
        Ok(bundle) => bundle,
        Err(_) => {
            return error(
                StatusCode::SERVICE_UNAVAILABLE,
                "pricing_unavailable",
                "Catalog pricing is temporarily unavailable.",
            )
        }
    };
    let manifest = RuntimePricingManifest::from_evidence(&app.pricing_manifest);
    let entries = bases
        .into_iter()
        .filter_map(|(candidate, base)| {
            // Strict Gemini admission is intentionally unavailable today; the catalog must not
            // advertise a personalized rate for a model that this key cannot execute.
            if candidate.provider_id == "google" {
                return None;
            }
            match resolve_pricing(
                &bundle,
                &PricingResolutionRequest {
                    account_id: auth.account_id.clone(),
                    provider_id: candidate.provider_id.clone(),
                    requested_model_id: candidate.model_id.clone(),
                    canonical_model_id: base.canonical_model_id.clone(),
                },
                &manifest,
            ) {
                PricingResolution::Resolved(resolved) => Some(priced_entry(
                    candidate.id.clone(),
                    base,
                    resolved.rule.payable_multiplier_bp,
                )),
                PricingResolution::Rejected(_) => None,
            }
        })
        .collect();
    response("strict", entries)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn integer_rate_projection_applies_account_multiplier_once() {
        let card = rate_card(
            RawRateCard {
                input: 5_000,
                output: 30_000,
                cache_read: 500,
                cache_write: 6_250,
                cache_write_1h: None,
            },
            5_000,
        );
        assert_eq!(card.input, "2500000000");
        assert_eq!(card.output, "15000000000");
        assert_eq!(card.cache_read, "250000000");
        assert_eq!(card.cache_write, "3125000000");
    }

    #[test]
    fn fast_and_long_context_rates_preserve_modifier_order() {
        let spec = metering::codex_catalog_at(1_785_369_601)
            .into_iter()
            .find(|model| model.id == "gpt-5.6-sol")
            .unwrap();
        let pricing = codex_pricing(&spec);
        let priority = pricing.priority.unwrap();
        assert_eq!(priority.input, 10_000);
        assert_eq!(priority.output, 60_000);
        let long = pricing.long_context.unwrap();
        assert_eq!(long.threshold_tokens, 272_000);
        assert_eq!(long.standard.input, 10_000);
        assert_eq!(long.standard.output, 45_000);
        assert_eq!(long.priority.unwrap().output, 90_000);
    }

    #[test]
    fn request_validation_is_bounded_and_provider_fixed() {
        let valid = PricingRequest {
            schema_version: 1,
            candidates: vec![Candidate {
                id: "openai/gpt-5.6".to_owned(),
                provider_id: "openai".to_owned(),
                model_id: "gpt-5.6".to_owned(),
            }],
        };
        assert!(validate(&valid));
        let mut invalid = valid;
        invalid.candidates[0].provider_id = "client-provider".to_owned();
        assert!(!validate(&invalid));
    }
}
