//! Authenticated, read-only account-policy preflight for the stateless unified router.
//!
//! The engine remains the policy authority: the router sends a bounded list built from its
//! aggregate catalog and receives only an ordered allow-list. No account, policy, rule, pricing or
//! credential identity is reflected in the response, logged, or cached here.

use axum::extract::rejection::JsonRejection;
use axum::extract::{ConnectInfo, State};
use axum::http::{HeaderMap, StatusCode};
use axum::response::{IntoResponse, Response};
use axum::Json;
use forward::{
    authed, resolve_client_key, resolve_pricing, AppState, PricingResolution,
    PricingResolutionRequest, RuntimePricingManifest,
};
use serde::Deserialize;
use serde_json::json;
use std::collections::BTreeSet;
use std::net::SocketAddr;

const SCHEMA_VERSION: u64 = 1;
const MAX_CANDIDATES: usize = 32;
const MAX_ID_BYTES: usize = 256;

#[derive(Debug, Deserialize)]
#[serde(deny_unknown_fields)]
pub(crate) struct PreflightRequest {
    schema_version: u64,
    candidates: Vec<Candidate>,
}

#[derive(Clone, Debug, Deserialize)]
#[serde(deny_unknown_fields)]
struct Candidate {
    /// Opaque correlation identity generated by the router from its canonical catalog entry.
    id: String,
    provider_id: String,
    canonical_model_id: String,
}

fn valid_id(value: &str) -> bool {
    !value.is_empty()
        && value.len() <= MAX_ID_BYTES
        && value.trim() == value
        && !value.bytes().any(|byte| byte.is_ascii_control())
}

fn validate(request: &PreflightRequest) -> bool {
    if request.schema_version != SCHEMA_VERSION
        || request.candidates.is_empty()
        || request.candidates.len() > MAX_CANDIDATES
    {
        return false;
    }

    let mut ids = BTreeSet::new();
    request.candidates.iter().all(|candidate| {
        valid_id(&candidate.id)
            && valid_id(&candidate.canonical_model_id)
            && matches!(
                candidate.provider_id.as_str(),
                "anthropic" | "openai" | "google"
            )
            && ids.insert(candidate.id.as_str())
    })
}

fn error(status: StatusCode, code: &'static str, message: &'static str) -> Response {
    (
        status,
        Json(json!({"error": {"code": code, "message": message}})),
    )
        .into_response()
}

fn response(mode: &'static str, allowed: Vec<String>) -> Response {
    (
        StatusCode::OK,
        Json(json!({
            "schema_version": SCHEMA_VERSION,
            "mode": mode,
            "allowed": allowed,
        })),
    )
        .into_response()
}

/// Return a sanitized policy allow-list without performing admission or any money mutation.
pub(crate) async fn preflight(
    State(app): State<AppState>,
    ConnectInfo(peer): ConnectInfo<SocketAddr>,
    headers: HeaderMap,
    payload: Result<Json<PreflightRequest>, JsonRejection>,
) -> Response {
    let Ok(Json(request)) = payload else {
        return error(
            StatusCode::BAD_REQUEST,
            "invalid_request",
            "Invalid router policy preflight request.",
        );
    };
    if !validate(&request) {
        return error(
            StatusCode::BAD_REQUEST,
            "invalid_request",
            "Invalid router policy preflight request.",
        );
    }

    let all = || {
        request
            .candidates
            .iter()
            .map(|candidate| candidate.id.clone())
            .collect()
    };

    // Forwarding-admin credentials are deliberately checked in memory before the billing
    // authority, matching live admission. A transient DB outage must not block admin canaries.
    if authed(&app, &headers, &peer) {
        return response("unrestricted", all());
    }

    let Some(billing) = app.billing.as_ref() else {
        return error(
            StatusCode::UNAUTHORIZED,
            "unauthorized",
            "Invalid API credential.",
        );
    };
    let auth = match resolve_client_key(billing, &headers).await {
        Ok(Some((_, auth))) => auth,
        Ok(None) => {
            return error(
                StatusCode::UNAUTHORIZED,
                "unauthorized",
                "Invalid API credential.",
            )
        }
        Err(_) => {
            return error(
                StatusCode::SERVICE_UNAVAILABLE,
                "policy_unavailable",
                "Account policy is temporarily unavailable.",
            )
        }
    };

    if !auth.strict_policy() {
        return response("unrestricted", all());
    }

    let bundle = match billing.pricing_read_bundle(&auth.account_id).await {
        Ok(bundle) => bundle,
        Err(_) => {
            return error(
                StatusCode::SERVICE_UNAVAILABLE,
                "policy_unavailable",
                "Account policy is temporarily unavailable.",
            )
        }
    };
    let manifest = RuntimePricingManifest::from_evidence(&app.pricing_manifest);
    let allowed = request
        .candidates
        .iter()
        .filter(|candidate| {
            // Gemini strict admission itself is intentionally unavailable. The preflight must not
            // promise an attempt which the money path will fail closed before reserve.
            if candidate.provider_id == "google" {
                return false;
            }
            matches!(
                resolve_pricing(
                    &bundle,
                    &PricingResolutionRequest {
                        account_id: auth.account_id.clone(),
                        provider_id: candidate.provider_id.clone(),
                        requested_model_id: candidate.canonical_model_id.clone(),
                        canonical_model_id: candidate.canonical_model_id.clone(),
                    },
                    &manifest,
                ),
                PricingResolution::Resolved(_)
            )
        })
        .map(|candidate| candidate.id.clone())
        .collect();
    response("strict", allowed)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn candidate(id: &str, provider_id: &str, canonical_model_id: &str) -> Candidate {
        Candidate {
            id: id.to_owned(),
            provider_id: provider_id.to_owned(),
            canonical_model_id: canonical_model_id.to_owned(),
        }
    }

    #[test]
    fn request_validation_is_bounded_and_fail_closed() {
        let valid = PreflightRequest {
            schema_version: SCHEMA_VERSION,
            candidates: vec![candidate(
                "anthropic/claude-sonnet-5",
                "anthropic",
                "claude-sonnet-5",
            )],
        };
        assert!(validate(&valid));

        for invalid in [
            PreflightRequest {
                schema_version: 2,
                candidates: valid.candidates.clone(),
            },
            PreflightRequest {
                schema_version: SCHEMA_VERSION,
                candidates: Vec::new(),
            },
            PreflightRequest {
                schema_version: SCHEMA_VERSION,
                candidates: vec![candidate("id", "unknown", "model")],
            },
            PreflightRequest {
                schema_version: SCHEMA_VERSION,
                candidates: vec![candidate(" id", "openai", "gpt-5.6-sol")],
            },
            PreflightRequest {
                schema_version: SCHEMA_VERSION,
                candidates: vec![candidate("id", "openai", &"m".repeat(MAX_ID_BYTES + 1))],
            },
            PreflightRequest {
                schema_version: SCHEMA_VERSION,
                candidates: vec![
                    candidate("same", "anthropic", "claude-sonnet-5"),
                    candidate("same", "openai", "gpt-5.6-sol"),
                ],
            },
        ] {
            assert!(!validate(&invalid), "invalid request was accepted");
        }

        let too_many = PreflightRequest {
            schema_version: SCHEMA_VERSION,
            candidates: (0..=MAX_CANDIDATES)
                .map(|index| candidate(&format!("model-{index}"), "openai", "gpt-5.6-sol"))
                .collect(),
        };
        assert!(!validate(&too_many));
    }
}
