import type { Language } from "@/components/i18n-provider";

const en = {
  navStart: "Start", navOverview: "Overview", navDevelopers: "Developers", navKeys: "API keys", navProviders: "Providers", navDocs: "Docs",
  providersEyebrow: "Developers", providersTitle: "Providers",
  providersSubtitle: "Two upstream providers on one key and one prepaid balance — both at the same flat −50% off official prices.",
  providerAnthropicApi: "Anthropic API", providerOpenaiApi: "OpenAI-compatible",
  providerAnthropicDesc: "The official Anthropic Messages API, byte-compatible with api.anthropic.com. Point Claude Code, Cursor, Cline or the Anthropic SDK at our endpoint — same requests, same responses, half the price.",
  providerOpenaiDesc: "An OpenAI-compatible API serving the GPT-5 line — Responses and Chat Completions with SSE streaming. Works with the official OpenAI SDKs, Codex CLI and any compatible tool on the same key and balance.",
  providerEndpoint: "Endpoint", providerCopyEndpoint: "Copy endpoint URL",
  providerModels: "models", providerOffOfficial: "off official prices",
  providersNote: "One sk-pool key and one balance cover both providers — switch by changing the base URL and model ID.",
  qsTitle: "Quick Start",
  qsAnthropicSubtitle: "Drop-in code to call Claude through our byte-compatible Anthropic Messages API.",
  qsOpenaiSubtitle: "Drop-in code to call the GPT-5 line through our OpenAI-compatible API.",
  qsStep1Title: "Get your API key",
  qsStep1Text: "Create an sk-pool key in the API keys section and set it as an environment variable:",
  qsStep2Title: "Make your first request",
  qsStep2AnthropicText: "Send the key in the x-api-key header and include anthropic-version: 2023-06-01 — official Anthropic SDKs add the version header automatically. Only the base URL changes; requests and responses match api.anthropic.com byte for byte.",
  qsStep2OpenaiText: "Send the same sk-pool key as Authorization: Bearer. The official OpenAI SDKs work unchanged — point base_url at our endpoint. Both Responses and Chat Completions are served; discover live models with GET /v1/models.",
  qsStep3Title: "Enable streaming",
  qsStep3Text: "Add \"stream\": true to the request body to receive the response as server-sent events:",
  qsEndpointsTitle: "Endpoint",
  qsAnthropicEndpointNote: "Creates a message using the Anthropic Messages API format. Supports text, images, tools, thinking and streaming.",
  qsOpenaiChatNote: "Creates a streaming or non-streaming response using the OpenAI Chat Completions format.",
  qsOpenaiResponsesNote: "Creates a streaming or non-streaming response using the OpenAI Responses API format.",
  qsModelRow: "Model",
  qsAnyClaude: "any supported Claude model",
  qsAnyGpt: "any supported GPT model",
  modelsBy: "by",
  navBilling: "Billing", navTopUp: "Balance",
  navGrowth: "Growth", navPromos: "Promo codes",
  navActivity: "Activity", navUsage: "Usage",
  navAccount: "Account", navProfile: "Profile", navSecurity: "Security",
  navSupportGroup: "Help", navSupport: "Support",
  supportEyebrow: "Help", supportTitle: "Support", supportSubtitle: "Chat with our AI assistant on Telegram — a human operator joins the same chat when your case needs one.",
  keysHelpTitle: "Stuck connecting your key?", keysHelpText: "Our AI support walks you through wiring it into your tool or SDK.", keysHelpCta: "Get help",
  loading: "Loading your account…", loadError: "Unable to load your account", loginPrompt: "Please log in to open your dashboard.",
  login: "Log in", logout: "Log out", closeMenu: "Close menu", menu: "Menu", topUp: "Top up", retry: "Retry",
  creditsLabel: "Balance", openProfile: "Open profile",
  manageKeys: "Manage API keys", getKey: "Get an API key", apiKey: "API key", used: "Used",
  balanceAfterDiscount: "Balance charged after discount", activeKeys: "API access", copy: "Copy", copied: "Copied",
  platformBalance: "Available credit", availableOnPlatform: "Available to spend on apiToken.sale", officialApiValue: "Equivalent official API usage",
  balanceValueAtDiscount: "At your current {discount}% discount, this balance covers approximately this much usage at official provider list prices.",
  worthApproximately: "Worth", inClaudeApiUsage: "in API usage at official prices",
  payPerOfficialDollar: "You pay ${rate} for every $1 of usage at official provider list prices.",
  apiAccess: "API access", usableKey: "Usable API key", usableKeys: "Usable API keys",
  checking: "Checking", statusUnavailable: "Unavailable", needsAttention: "Needs attention", ready: "Ready", setupRequired: "Setup required",
  checkingKeyStatus: "Checking your API keys…",
  keysReady: "Your API access is ready.", noKeysOverview: "Create one key to start making requests.",
  keysNeedAttention: "Your existing keys are revoked, expired, or at their spending limit.", engineNotReady: "Your API account is not ready yet. Retry shortly or contact support if this persists.", keysUnavailable: "Key status is temporarily unavailable.",
  apiAccessBlocked: "API access needs attention", keysNeedAttentionTitle: "Review your API keys",
  balanceEmptyTitle: "Your balance is empty", balanceEmptyText: "Top up before making your next API request.",
  balanceLowTitle: "Your balance is running low", balanceLowText: "Add credit now to avoid interrupted API requests.",
  keysDataLoading: "Loading API keys…", ledgerDataLoading: "Loading recent ledger history…", usageDataLoading: "Loading the 30-day usage summary…",
  keysDataUnavailable: "API keys could not be loaded. Other dashboard sections remain available.", ledgerDataUnavailable: "Ledger history could not be loaded. Balance and account data remain available.", usageDataUnavailable: "Detailed 30-day usage could not be loaded. Recent ledger details may still be available.",
  chargeEventsThisMonth: "Charge events: {count}", viewUsage: "View usage",
  officialValue30d: "Official list-price value (30d)",
  currentPricing: "Current pricing", discount: "off",
  flatRate: "Flat rate −50%",
  flatExplainer: "Every account pays half of the official provider list price — one flat 50% discount on every Claude and GPT model, with no volume conditions and nothing to maintain.",
  flatEveryModel: "The discount applies automatically to every request on every model.",
  howPricingWorks: "How pricing works",
  providersOverviewText: "Anthropic and OpenAI on one key — flat −50% off official prices.",
  browseProviders: "View providers",
  keysEyebrow: "Developers", keysTitle: "API keys", keysSubtitle: "Create, monitor, and secure keys for every Claude and GPT integration.",
  apiEndpoint: "API endpoint", anthropicCompatible: "Anthropic-compatible", shownOnce: "Shown once",
  agentDockEyebrow: "Quick setup", agentDockTitle: "Connect your coding tool", agentDockText: "One key for both APIs. Pick the tool and your system, copy the setup, and run it in the terminal.",
  agentDockTabClaude: "Claude Code", agentDockTabCodex: "Codex · OpenAI",
  agentDockToolLabel: "Tool", agentDockOsLabel: "System", agentDockOsMac: "macOS / Linux", agentDockOsPowershell: "Windows · PowerShell", agentDockOsCmd: "Windows · CMD",
  agentDockTerminal: "Terminal setup", agentDockCopyTerminal: "Copy setup commands", agentDockCopyTemplate: "Copy setup template", agentDockTerminalCopied: "Setup copied", agentDockDocs: "Open full docs",
  agentDockStepOne: "Create key", agentDockStepTwo: "Copy commands", agentDockStepThree: "Run Claude", agentDockStepThreeCodex: "Run Codex",
  agentDockAgentTitle: "Using a coding agent?", agentDockAgentText: "Give it the complete integration brief instead.", agentDockCopy: "Copy agent brief", agentDockCopyWithKey: "Copy brief + key", agentDockCopied: "Brief copied",
  agentDockKeyIncluded: "Key ready", agentDockKeyPlaceholder: "Setup template", agentDockSecretNote: "The setup saves your secret in ~/.zshrc so it works in new terminals. Use only on a trusted computer.", agentDockTemplateNote: "Create a key to replace YOUR_SK_POOL_API_KEY and save it in ~/.zshrc.",
  agentDockSecretNoteWin: "setx saves your secret for new terminal windows; the set/$env: lines apply it to the current one. Use only on a trusted computer.", agentDockTemplateNoteWin: "Create a key to replace YOUR_SK_POOL_API_KEY. setx keeps it for new terminal windows; the set/$env: lines apply it right away.",
  copyNewKeyNow: "Your new API key is ready", rawSecretWarning: "Copy it as many times as you need during this dashboard session. After you dismiss this panel, leave the dashboard, or refresh, the raw key cannot be shown again.",
  savedKey: "Done", openInDocs: "Open in docs →", docsShort: "Docs ↗", universalKeys: "Universal keys", optionalLabel: "Optional label", newKey: "New key",
  noKeys: "No API keys yet.", unlabelledKey: "Unlabelled key", created: "created", spent: "spent", revoke: "Revoke",
  revokeConfirm: "Revoke this API key? This cannot be undone.", createKeyError: "Unable to create the key", revokeKeyError: "Unable to revoke the key",
  quickStart: "Quick start", creditsEyebrow: "Billing", creditsTitle: "Top up balance", creditsSubtitle: "Enter the whole USD amount you want to add to your API balance.",
  currentBalance: "Current balance", available: "Available", reserved: "Reserved", inFlight: "In-flight requests",
  cryptoCheckout: "Crypto checkout", anyWholeAmount: "Top up any whole USD amount",
  checkoutHelp: "No preset amounts and no decimals. Pick a payment method below; the provider shows the final amount to pay.",
  creating: "Creating…", continuePayment: "Continue to payment", createCheckoutError: "Unable to create checkout",
  checkoutPending: "Checkout {id} is {status}. Refresh later to obtain its payment URL.",
  youReceive: "You receive", inClaudeApi: "of API usage at official prices", officialPricing: "official list prices",
  valueOfBalance: "≈ {value} of official API usage", quickAmounts: "Quick amounts",
  perDollar: "Every $1 you pay is worth {mult} of API usage at official provider list prices.",
  nextTierNudge: "Reach {tier} (−{discount}%) and {amount} becomes ≈ {value}.", valueMultiplier: "value",
  enterAmount: "Enter an amount to see what you get.",
  topupUnlocks: "Reach {tier} (−{discount}%) by spending this within the calendar month — usage is then charged at −{discount}%",
  topupUpsell: "Spend {amount}+ this month → {tier} (−{discount}%), usage charged at that rate",
  topupNoTier: "Top up ≥ {amount} to reach {tier} (−{discount}%)",
  topupNext: "Top up {amount}+ total → {tier} (−{discount}%)",
  usageLast30Days: "Usage · 30 days", loadingUsageSummary: "Loading your recent usage…",
  usageSummaryUnavailable: "The 30-day usage summary is temporarily unavailable.",
  usageChargedAndRequests: "{charged} charged · {requests} requests",
  startFirstRequest: "Make your first API request", startFirstRequestText: "Your account is ready. Complete these three steps to connect a compatible tool — Claude Code, Codex, or any SDK.",
  createFirstKey: "Create a key", createFirstKeyHint: "Issue a secure API credential",
  connectYourTool: "Connect your tool", connectYourToolHint: "Add the endpoint and key",
  makeFirstRequest: "Make a request", makeFirstRequestHint: "Confirm the integration works",
  recentActivity: "Recent activity", latestAccountActivity: "Latest account activity", viewAllActivity: "View all activity",
  loadingRecentActivity: "Loading recent activity…", recentActivityUnavailable: "Recent activity is temporarily unavailable.",
  apiUsageActivity: "API usage", accountAdjustment: "Account adjustment",
  topupHistory: "Top-up history", histPaid: "Paid", histDiscount: "Discount", histApiValue: "API received",
  noTopups: "No top-ups yet.",
  usageEyebrow: "Activity", usageTitle: "Usage", usageSubtitle: "Exact settled usage for one rolling 30-day window, valued at official provider list prices.",
  sessionSavingTitle: "Save tokens by working in long sessions.", sessionSavingText: "Long sessions can take advantage of prompt caching, reducing repeated-context cost.",
  apiRouting: "API routing", availableBalance: "Available balance", totalCharged: "total balance charged after discount",
  sameBalance: "The same balance covers every Claude and GPT model exposed by the gateway.", apiHealth: "API health",
  analyticsPending: "Analytics pending", healthPending: "Request-level health will appear when the backend exposes authoritative metrics.",
  successRate: "Success rate", averageLatency: "Avg latency", requests: "Requests", officialSpend: "Official list-price value",
  perRequestPending: "Per-request metric pending", balanceCharged: "Balance charged", afterDiscount: "After discount",
  charged30d: "Credits charged (30d)", settledCredits: "Settled after the rate active at each event", listPriceEquivalent: "List-price equivalent, not a provider invoice", currentValue: "current value",
  activeDiscount: "Active discount",
  usageAnalytics: "Usage analytics", chartsPending: "Charts and model-level breakdowns will appear when the backend exposes authoritative request metrics.",
  comingSoon: "Coming soon", usageTrend: "Usage trend", officialSpendOverTime: "Official API spend over time",
  modelBreakdown: "Model breakdown", spendByModel: "Spend grouped by model", transactions: "Recent transactions",
  time: "Time", type: "Type", reference: "Reference", amount: "Amount", noLedger: "No ledger activity yet.",
  topupType: "Top-up", adjustType: "Adjustment", billedEventOne: "{n} billed event", billedEventsFew: "{n} billed events", apiRequestsN: "{n} billed events", moreRows: "+{n} more billed events",
  claudeApiReceived: "Official API value received", atOfficialPrices: "at official list prices",
  receivedFromCharged: "from {charged} charged · {mult} value", receivedEmpty: "No usage yet — make your first call",
  dailyBurn: "Daily burn", avgPerActiveDay: "avg per active day",
  usageOverTime: "Settled usage over time", last30Official: "Rolling 30 days · official list-price value",
  chartWindowLabel: "Rolling 30 days · UTC day buckets", chartTotal: "Total", otherModels: "Other", shareOfUse: "Share of spend",
  chartDayLabel: "{date}: {value} at official list prices", tableScrollHint: "Swipe or scroll horizontally to see every column.",
  periodSummary: "30-day summary", chargeEvents: "Charge events", billedEvents: "Billed events", peakDay: "Peak UTC day",
  dailyAverage: "Daily average", noChargesPeriod: "No billed usage in the rolling 30-day window.",
  usageByKey: "Usage by API key", usageByKeySub: "Exact settled usage grouped by the key that made each billed request.",
  keysCount: "Keys", visibleCharges: "Visible charges", valueColumn: "Value", officialValueCol: "List-price value", chargedCol: "Charged", systemCharge: "System",
  tokensAndModels: "Tokens & models", tokensAndModelsSub: "Token counts and exact stored list-price value, by model and provider.",
  tokensPending: "Per-model token usage appears once your requests are metered by the engine.",
  inputTokens: "Input tokens", outputTokens: "Output tokens", cacheTokens: "Cache tokens", webSearchLabel: "Web search",
  cacheReadLabel: "Cache read", cacheWriteLabel: "Cache write", legacyUnattributed: "Legacy / unattributed", historicalUsage: "Historical value",
  bucketAttributionNote: "This value predates detailed token-bucket attribution. It is shown separately so bucket values reconcile exactly to the official total.",
  model: "Model", inputShort: "Input", outputShort: "Output", cacheShort: "Cache", cacheRdShort: "Cache rd", cacheWrShort: "Cache wr",
  providerAnthropic: "Anthropic", providerOpenAi: "OpenAI",
  profileTitle: "Profile", profileSubtitle: "Verified account details from the commercial backend.", email: "Email",
  accountDetails: "Account details",
  displayName: "Display name", userId: "User ID", supportId: "Keep this ID handy when asking support to inspect API usage or billing events.",
  verified: "verified", pending: "pending", save: "Save", saving: "Saving…", profileSaved: "Saved", profileSaveError: "Unable to save your display name",
  telegram: "Telegram", notConnected: "Not connected", telegramHelp: "Connect Telegram to receive balance and usage updates.",
  connectTelegram: "Connect Telegram", botLanguage: "Bot language", english: "English", russian: "Русский",
  lowBalanceAlerts: "Low balance alerts", paymentNotifications: "Payment notifications", weeklyDigest: "Weekly usage digest",
  lowBalanceThreshold: "Low balance threshold, USD", securityHelp: "Review account access and available security controls.",
  securityTitle: "Security", securitySubtitle: "Your session is stored in a Secure, HttpOnly backend cookie.",
  twoFactorHelp: "Use Google Authenticator, Authy, 1Password or any TOTP client when two-factor authentication becomes available.",
  twoFactorTitle: "Two-factor authentication", twoFactorOn: "On", twoFactorOff: "Off",
  twoFactorGateHelp: "Protect API-key creation and guardrail changes with a code from your authenticator app. This does not add a second step to dashboard sign-in.",
  twoFactorRecoveryHelp: "No self-service recovery codes are issued yet. Keep the manual setup key in a secure password manager; contact support if you lose access to your authenticator.",
  twoFactorScan: "Scan with Google Authenticator (or any TOTP app), then enter the 6-digit code.",
  twoFactorManual: "Or enter the key manually", twoFactorVerify: "Verify & enable", twoFactorDisable: "Disable 2FA",
  twoFactorDisableHelp: "Enter a current code to turn off 2FA.",
  twoFactorError: "Couldn't start 2FA setup. Please try again.", twoFactorCodeInvalid: "Invalid or expired code. Try again.",
  twoFactorCodeRequired: "Enter your 6-digit 2FA code to issue a key.",
  twoFactorCodePlaceholder: "2FA code", twoFactorCodeLabel: "6-digit 2FA code", cancel: "Cancel",
  enable2fa: "Enable 2FA", backendRequired: "Backend support required", password: "Password", currentPassword: "Current password",
  newPassword: "New password", updatePassword: "Update password", passwordPending: "Password changes are not connected yet",
  oauthAccess: "Social sign-in", oauthAccessText: "This account signs in through Google or GitHub. It has no password stored on apiToken.sale.",
  activeSessions: "Active sessions", thisDevice: "This device", activeNow: "Active now", logoutSession: "Log out this session",
  promoEyebrow: "Rewards", promoTitle: "Promo codes",
  promoSubtitle: "Enter a promo code to add balance to your account.", activate: "Activate",
  promoPending: "", myActivations: "My activations", code: "Code", reward: "Reward",
  date: "Date", promoCredit: "Promo credit", noPromos: "No promo-code activations are visible in your recent ledger.",
  promoInput: "Promo code", promoAdded: "Added to your balance:", promoInvalid: "Enter a valid promo code.",
  promoPlaceholder: "For example, WELCOME26",
  promoHelp: "Codes come from our news channel and partners — each one credits balance to your account once.",
} as const;

export type DashboardCopy = { [K in keyof typeof en]: string };

const ru: DashboardCopy = {
  navStart: "Начало", navOverview: "Обзор", navDevelopers: "Разработчикам", navKeys: "API-ключи", navProviders: "Провайдеры", navDocs: "Документация",
  providersEyebrow: "Разработчикам", providersTitle: "Провайдеры",
  providersSubtitle: "Два апстрим-провайдера на одном ключе и одном предоплаченном балансе — оба с одинаковой плоской скидкой −50% от официальных цен.",
  providerAnthropicApi: "Anthropic API", providerOpenaiApi: "OpenAI-совместимый",
  providerAnthropicDesc: "Официальный Anthropic Messages API, байт-в-байт совместимый с api.anthropic.com. Направьте Claude Code, Cursor, Cline или Anthropic SDK на наш эндпоинт — те же запросы, те же ответы, половина цены.",
  providerOpenaiDesc: "OpenAI-совместимый API с линейкой GPT-5 — Responses и Chat Completions с SSE-стримингом. Работает с официальными SDK OpenAI, Codex CLI и любым совместимым инструментом на том же ключе и балансе.",
  providerEndpoint: "Эндпоинт", providerCopyEndpoint: "Скопировать URL эндпоинта",
  providerModels: "моделей", providerOffOfficial: "от официальных цен",
  providersNote: "Один ключ sk-pool и один баланс покрывают обоих провайдеров — переключение = смена base URL и ID модели.",
  qsTitle: "Quick Start",
  qsAnthropicSubtitle: "Готовый код для вызова Claude через наш байт-в-байт совместимый Anthropic Messages API.",
  qsOpenaiSubtitle: "Готовый код для вызова линейки GPT-5 через наш OpenAI-совместимый API.",
  qsStep1Title: "Получите API-ключ",
  qsStep1Text: "Создайте ключ sk-pool в разделе «API-ключи» и сохраните его в переменной окружения:",
  qsStep2Title: "Сделайте первый запрос",
  qsStep2AnthropicText: "Передавайте ключ в заголовке x-api-key и добавляйте anthropic-version: 2023-06-01 — официальные SDK Anthropic добавляют версию сами. Меняется только base URL; запросы и ответы совпадают с api.anthropic.com байт-в-байт.",
  qsStep2OpenaiText: "Тот же ключ sk-pool передавайте как Authorization: Bearer. Официальные SDK OpenAI работают без изменений — укажите base_url нашего эндпоинта. Доступны Responses и Chat Completions; актуальные модели — GET /v1/models.",
  qsStep3Title: "Включите стриминг",
  qsStep3Text: "Добавьте \"stream\": true в тело запроса, чтобы получать ответ как server-sent events:",
  qsEndpointsTitle: "Эндпоинт",
  qsAnthropicEndpointNote: "Создаёт сообщение в формате Anthropic Messages API. Поддерживает текст, изображения, инструменты, размышление и стриминг.",
  qsOpenaiChatNote: "Создаёт стриминговый или обычный ответ в формате OpenAI Chat Completions.",
  qsOpenaiResponsesNote: "Создаёт стриминговый или обычный ответ в формате OpenAI Responses API.",
  qsModelRow: "Модель",
  qsAnyClaude: "любая поддерживаемая модель Claude",
  qsAnyGpt: "любая поддерживаемая модель GPT",
  modelsBy: "от",
  navBilling: "Оплата", navTopUp: "Баланс",
  navGrowth: "Развитие", navPromos: "Промокоды",
  navActivity: "Активность", navUsage: "Использование",
  navAccount: "Аккаунт", navProfile: "Профиль", navSecurity: "Безопасность",
  navSupportGroup: "Помощь", navSupport: "Поддержка",
  supportEyebrow: "Помощь", supportTitle: "Поддержка", supportSubtitle: "Пишите нашему ИИ-ассистенту в Telegram — живой оператор подключается в тот же чат, когда вопрос требует человека.",
  keysHelpTitle: "Не выходит подключить ключ?", keysHelpText: "ИИ-поддержка проведёт по интеграции в ваш инструмент или SDK.", keysHelpCta: "Помощь",
  loading: "Загружаем аккаунт…", loadError: "Не удалось загрузить аккаунт", loginPrompt: "Войдите, чтобы открыть личный кабинет.",
  login: "Войти", logout: "Выйти", closeMenu: "Закрыть меню", menu: "Меню", topUp: "Пополнить", retry: "Повторить",
  creditsLabel: "Баланс", openProfile: "Открыть профиль",
  manageKeys: "Управлять ключами", getKey: "Получить API-ключ", apiKey: "API-ключ", used: "Использовано",
  balanceAfterDiscount: "Списано с баланса после скидки", activeKeys: "Доступ к API", copy: "Копировать", copied: "Скопировано",
  platformBalance: "Доступный баланс", availableOnPlatform: "Доступно для использования на apiToken.sale", officialApiValue: "Эквивалент официального использования API",
  balanceValueAtDiscount: "С вашей текущей скидкой {discount}% этот баланс покрывает примерно такой объём использования по официальным листовым ценам провайдеров.",
  worthApproximately: "Это примерно", inClaudeApiUsage: "использования API по официальным ценам",
  payPerOfficialDollar: "Вы платите ${rate} за каждый $1 использования по официальной листовой цене.",
  apiAccess: "Доступ к API", usableKey: "Рабочий API-ключ", usableKeys: "Рабочие API-ключи",
  checking: "Проверяем", statusUnavailable: "Недоступно", needsAttention: "Нужно внимание", ready: "Готово", setupRequired: "Нужна настройка",
  checkingKeyStatus: "Проверяем состояние API-ключей…",
  keysReady: "Доступ к API готов.", noKeysOverview: "Создайте один ключ, чтобы начать отправлять запросы.",
  keysNeedAttention: "Существующие ключи отозваны, истекли или исчерпали лимит расходов.", engineNotReady: "API-аккаунт ещё не готов. Повторите попытку позже или обратитесь в поддержку.", keysUnavailable: "Статус ключей временно недоступен.",
  apiAccessBlocked: "Проверьте доступ к API", keysNeedAttentionTitle: "Проверьте API-ключи",
  balanceEmptyTitle: "Баланс закончился", balanceEmptyText: "Пополните его перед следующим API-запросом.",
  balanceLowTitle: "Баланс почти закончился", balanceLowText: "Пополните его сейчас, чтобы API-запросы не прервались.",
  keysDataLoading: "Загружаем API-ключи…", ledgerDataLoading: "Загружаем недавнюю историю операций…", usageDataLoading: "Загружаем сводку использования за 30 дней…",
  keysDataUnavailable: "Не удалось загрузить API-ключи. Остальные разделы кабинета доступны.", ledgerDataUnavailable: "Не удалось загрузить историю операций. Баланс и данные аккаунта доступны.", usageDataUnavailable: "Не удалось загрузить подробную статистику за 30 дней. Недавние данные журнала могут оставаться доступными.",
  chargeEventsThisMonth: "Списаний зафиксировано: {count}", viewUsage: "Открыть использование",
  officialValue30d: "Ценность по листовой цене (30 дн.)",
  currentPricing: "Текущая цена", discount: "скидка",
  flatRate: "Единая ставка −50%",
  flatExplainer: "Каждый аккаунт платит половину официальной листовой цены провайдера — одна плоская скидка 50% на все модели Claude и GPT, без условий по объёму и без удержаний.",
  flatEveryModel: "Скидка применяется автоматически к каждому запросу на любой модели.",
  howPricingWorks: "Как устроена цена",
  providersOverviewText: "Anthropic и OpenAI на одном ключе — плоские −50% от официальных цен.",
  browseProviders: "Провайдеры",
  keysEyebrow: "Разработчикам", keysTitle: "API-ключи", keysSubtitle: "Создавайте, отслеживайте и защищайте ключи для интеграций Claude и GPT.",
  apiEndpoint: "Адрес API", anthropicCompatible: "Совместим с Anthropic", shownOnce: "Показывается один раз",
  agentDockEyebrow: "Быстрая настройка", agentDockTitle: "Подключите инструмент разработки", agentDockText: "Один ключ для обоих API. Выберите инструмент и систему, скопируйте команды и запустите их в терминале.",
  agentDockTabClaude: "Claude Code", agentDockTabCodex: "Codex · OpenAI",
  agentDockToolLabel: "Инструмент", agentDockOsLabel: "Система", agentDockOsMac: "macOS / Linux", agentDockOsPowershell: "Windows · PowerShell", agentDockOsCmd: "Windows · CMD",
  agentDockTerminal: "Настройка терминала", agentDockCopyTerminal: "Скопировать настройку", agentDockCopyTemplate: "Скопировать шаблон", agentDockTerminalCopied: "Настройка скопирована", agentDockDocs: "Открыть документацию",
  agentDockStepOne: "Создать ключ", agentDockStepTwo: "Скопировать команды", agentDockStepThree: "Запустить Claude", agentDockStepThreeCodex: "Запустить Codex",
  agentDockAgentTitle: "Работаете с ИИ-агентом?", agentDockAgentText: "Передайте ему готовое техническое задание.", agentDockCopy: "Скопировать задание", agentDockCopyWithKey: "Задание с ключом", agentDockCopied: "Задание скопировано",
  agentDockKeyIncluded: "Ключ готов", agentDockKeyPlaceholder: "Шаблон настройки", agentDockSecretNote: "Настройка сохранит секрет в ~/.zshrc для новых терминалов. Используйте её только на доверенном компьютере.", agentDockTemplateNote: "Создайте ключ — YOUR_SK_POOL_API_KEY заменится и сохранится в ~/.zshrc.",
  agentDockSecretNoteWin: "setx сохранит секрет для новых окон терминала; строки set/$env: включают его в текущем. Используйте только на доверенном компьютере.", agentDockTemplateNoteWin: "Создайте ключ и подставьте вместо YOUR_SK_POOL_API_KEY. setx сохранит его для новых окон терминала; строки set/$env: включают его сразу.",
  copyNewKeyNow: "Новый API-ключ готов", rawSecretWarning: "Копируйте его столько раз, сколько нужно в этой сессии кабинета. После закрытия панели, выхода из кабинета или обновления страницы исходный ключ нельзя будет показать снова.",
  savedKey: "Готово", openInDocs: "Открыть в документации →", docsShort: "Документация ↗", universalKeys: "Универсальные ключи", optionalLabel: "Необязательное название", newKey: "Новый ключ",
  noKeys: "API-ключей пока нет.", unlabelledKey: "Ключ без названия", created: "создан", spent: "израсходовано", revoke: "Отозвать",
  revokeConfirm: "Отозвать этот API-ключ? Действие нельзя отменить.", createKeyError: "Не удалось создать ключ", revokeKeyError: "Не удалось отозвать ключ",
  quickStart: "Быстрый старт", creditsEyebrow: "Оплата", creditsTitle: "Пополнение баланса", creditsSubtitle: "Введите целую сумму в долларах, которую хотите добавить на баланс API.",
  currentBalance: "Текущий баланс", available: "Доступно", reserved: "Зарезервировано", inFlight: "Активные запросы",
  cryptoCheckout: "Оплата криптовалютой", anyWholeAmount: "Пополнить на любую целую сумму",
  checkoutHelp: "Нет фиксированных пакетов и дробных сумм. Выберите способ оплаты ниже — сервис покажет итоговую сумму к оплате.",
  creating: "Создаём…", continuePayment: "Перейти к оплате", createCheckoutError: "Не удалось создать платёж",
  checkoutPending: "Платёж {id} имеет статус {status}. Обновите страницу позже, чтобы получить ссылку на оплату.",
  youReceive: "Вы получаете", inClaudeApi: "использования API по официальным ценам", officialPricing: "по официальным листовым ценам",
  valueOfBalance: "≈ {value} официального использования API", quickAmounts: "Быстрый выбор",
  perDollar: "Каждый $1 оплаты = {mult} использования API по официальным листовым ценам провайдеров.",
  nextTierNudge: "Дойдите до {tier} (−{discount}%) — и {amount} превратятся в ≈ {value}.", valueMultiplier: "ценность",
  enterAmount: "Введите сумму, чтобы увидеть, что получите.",
  topupUnlocks: "Достигнешь тарифа {tier} (−{discount}%), потратив столько за календарный месяц — и списания пойдут по −{discount}%",
  topupUpsell: "Потрать {amount}+ за месяц → {tier} (−{discount}%), списания по этой ставке",
  topupNoTier: "Пополни ≥ {amount}, чтобы получить {tier} (−{discount}%)",
  topupNext: "Пополни в сумме {amount}+ → {tier} (−{discount}%)",
  usageLast30Days: "Использование · 30 дней", loadingUsageSummary: "Загружаем недавнее использование…",
  usageSummaryUnavailable: "Сводка за 30 дней временно недоступна.",
  usageChargedAndRequests: "Списано {charged} · запросов: {requests}",
  startFirstRequest: "Отправьте первый API-запрос", startFirstRequestText: "Аккаунт готов. Выполните три шага, чтобы подключить совместимый инструмент — Claude Code, Codex или любой SDK.",
  createFirstKey: "Создайте ключ", createFirstKeyHint: "Выпустите защищённый API-ключ",
  connectYourTool: "Подключите инструмент", connectYourToolHint: "Добавьте адрес API и ключ",
  makeFirstRequest: "Отправьте запрос", makeFirstRequestHint: "Убедитесь, что интеграция работает",
  recentActivity: "Недавняя активность", latestAccountActivity: "Последние операции", viewAllActivity: "Вся активность",
  loadingRecentActivity: "Загружаем последние операции…", recentActivityUnavailable: "Последние операции временно недоступны.",
  apiUsageActivity: "Использование API", accountAdjustment: "Корректировка аккаунта",
  topupHistory: "История пополнений", histPaid: "Оплачено", histDiscount: "Скидка", histApiValue: "Получено API",
  noTopups: "Пополнений пока нет.",
  usageEyebrow: "Активность", usageTitle: "Использование", usageSubtitle: "Точные закрытые начисления за единое скользящее окно 30 дней, оценённые по официальным листовым ценам провайдеров.",
  sessionSavingTitle: "Экономьте токены в длинных сессиях.", sessionSavingText: "Кэширование промпта сокращает стоимость повторяющегося контекста в длинных сессиях.",
  apiRouting: "Маршрутизация API", availableBalance: "Доступный баланс", totalCharged: "всего списано с учётом скидки",
  sameBalance: "Единый баланс покрывает все модели Claude и GPT, доступные через шлюз.", apiHealth: "Состояние API",
  analyticsPending: "Аналитика готовится", healthPending: "Метрики запросов появятся после подключения подтверждённой аналитики бэкенда.",
  successRate: "Успешность", averageLatency: "Средняя задержка", requests: "Запросы", officialSpend: "Ценность по официальной листовой цене",
  perRequestPending: "Метрика по запросам готовится", balanceCharged: "Списано с баланса", afterDiscount: "После скидки",
  charged30d: "Списано кредитов (30 дн.)", settledCredits: "Закрыто по ставке каждого события", listPriceEquivalent: "Эквивалент листовой цены, не счёт провайдера", currentValue: "текущая ценность",
  activeDiscount: "Активная скидка",
  usageAnalytics: "Аналитика использования", chartsPending: "Графики и разбивка по моделям появятся после подключения подтверждённых метрик бэкенда.",
  comingSoon: "Скоро", usageTrend: "Динамика использования", officialSpendOverTime: "Расход по официальным ценам во времени",
  modelBreakdown: "Разбивка по моделям", spendByModel: "Расход по каждой модели", transactions: "Недавние операции",
  time: "Время", type: "Тип", reference: "Ссылка", amount: "Сумма", noLedger: "Операций пока нет.",
  topupType: "Пополнение", adjustType: "Коррекция", billedEventOne: "{n} тарифицированное событие", billedEventsFew: "{n} тарифицированных события", apiRequestsN: "{n} тарифицированных событий", moreRows: "+{n} тарифицированных событий",
  claudeApiReceived: "Получено официальной ценности API", atOfficialPrices: "по официальным листовым ценам",
  receivedFromCharged: "из {charged} списанных · {mult} ценности", receivedEmpty: "Пока нет расхода — сделайте первый запрос",
  dailyBurn: "Расход в день", avgPerActiveDay: "в среднем за активный день",
  usageOverTime: "Закрытое использование по времени", last30Official: "Скользящие 30 дней · ценность по листовой цене",
  chartWindowLabel: "Скользящие 30 дней · дни по UTC", chartTotal: "Итого", otherModels: "Прочее", shareOfUse: "Доля расхода",
  chartDayLabel: "{date}: {value} по официальной листовой цене", tableScrollHint: "Проведите пальцем или прокрутите горизонтально, чтобы увидеть все столбцы.",
  periodSummary: "Сводка за 30 дней", chargeEvents: "Списания", billedEvents: "Тарифицированные события", peakDay: "Пиковый день UTC",
  dailyAverage: "Среднее в день", noChargesPeriod: "В скользящем 30-дневном окне нет тарифицированного использования.",
  usageByKey: "Использование по ключам", usageByKeySub: "Точные закрытые начисления, сгруппированные по ключу каждого тарифицированного запроса.",
  keysCount: "Ключей", visibleCharges: "Видимых списаний", valueColumn: "Ценность", officialValueCol: "По листовой цене", chargedCol: "Списано", systemCharge: "Система",
  tokensAndModels: "Токены и модели", tokensAndModelsSub: "Число токенов и точная сохранённая ценность по листовым ценам, по моделям и провайдерам.",
  tokensPending: "Разбивка токенов по моделям появится, когда движок начнёт учитывать запросы.",
  inputTokens: "Входные токены", outputTokens: "Выходные токены", cacheTokens: "Кэш-токены", webSearchLabel: "Веб-поиск",
  cacheReadLabel: "Кэш чтение", cacheWriteLabel: "Кэш запись", legacyUnattributed: "Старое / без атрибуции", historicalUsage: "Историческая ценность",
  bucketAttributionNote: "Эта ценность появилась до подробного учёта по типам токенов. Она показана отдельно, чтобы сумма категорий точно совпадала с общим итогом.",
  model: "Модель", inputShort: "Вход", outputShort: "Выход", cacheShort: "Кэш", cacheRdShort: "Кэш чт", cacheWrShort: "Кэш зп",
  providerAnthropic: "Anthropic", providerOpenAi: "OpenAI",
  profileTitle: "Профиль", profileSubtitle: "Подтверждённые данные аккаунта из коммерческого бэкенда.", email: "Email",
  accountDetails: "Данные аккаунта",
  displayName: "Имя", userId: "ID пользователя", supportId: "Сохраните этот ID: он поможет поддержке найти данные по использованию API или оплате.",
  verified: "подтверждён", pending: "ожидает подтверждения", save: "Сохранить", saving: "Сохраняем…", profileSaved: "Сохранено", profileSaveError: "Не удалось сохранить имя",
  telegram: "Telegram", notConnected: "Не подключён", telegramHelp: "Подключите Telegram для уведомлений о балансе и использовании.",
  connectTelegram: "Подключить Telegram", botLanguage: "Язык бота", english: "English", russian: "Русский",
  lowBalanceAlerts: "Низкий баланс", paymentNotifications: "Уведомления об оплате", weeklyDigest: "Еженедельный отчёт",
  lowBalanceThreshold: "Порог низкого баланса, USD", securityHelp: "Проверьте доступ к аккаунту и доступные настройки безопасности.",
  securityTitle: "Безопасность", securitySubtitle: "Сессия хранится в защищённой HttpOnly cookie бэкенда.",
  twoFactorHelp: "Используйте Google Authenticator, Authy, 1Password или другой TOTP-клиент, когда двухфакторная защита станет доступна.",
  twoFactorTitle: "Двухфакторная аутентификация", twoFactorOn: "Вкл", twoFactorOff: "Выкл",
  twoFactorGateHelp: "Защитите создание API-ключей и изменение ограничений кодом из приложения-аутентификатора. Это не добавляет второй шаг ко входу в кабинет.",
  twoFactorRecoveryHelp: "Коды восстановления пока не выдаются. Сохраните ключ ручной настройки в защищённом менеджере паролей; если потеряете доступ к приложению, обратитесь в поддержку.",
  twoFactorScan: "Отсканируйте в Google Authenticator (или другом TOTP-приложении) и введите 6-значный код.",
  twoFactorManual: "Или введите ключ вручную", twoFactorVerify: "Проверить и включить", twoFactorDisable: "Отключить 2FA",
  twoFactorDisableHelp: "Введите текущий код, чтобы отключить 2FA.",
  twoFactorError: "Не удалось начать настройку 2FA. Попробуйте ещё раз.", twoFactorCodeInvalid: "Неверный или просроченный код. Попробуйте снова.",
  twoFactorCodeRequired: "Введите 6-значный код 2FA для выпуска ключа.",
  twoFactorCodePlaceholder: "Код 2FA", twoFactorCodeLabel: "6-значный код 2FA", cancel: "Отмена",
  enable2fa: "Включить 2FA", backendRequired: "Требуется поддержка бэкенда", password: "Пароль", currentPassword: "Текущий пароль",
  newPassword: "Новый пароль", updatePassword: "Обновить пароль", passwordPending: "Смена пароля пока не подключена",
  oauthAccess: "Вход через соцсеть", oauthAccessText: "Этот аккаунт входит через Google или GitHub. Пароль на apiToken.sale не хранится.",
  activeSessions: "Активные сессии", thisDevice: "Это устройство", activeNow: "Активно сейчас", logoutSession: "Завершить эту сессию",
  promoEyebrow: "Награды", promoTitle: "Промокоды",
  promoSubtitle: "Введите промокод, чтобы пополнить баланс.", activate: "Активировать",
  promoPending: "", myActivations: "Мои активации", code: "Код", reward: "Награда",
  date: "Дата", promoCredit: "Промо-начисление", noPromos: "В недавней истории нет активаций промокодов.",
  promoInput: "Промокод", promoAdded: "Начислено на баланс:", promoInvalid: "Введите корректный промокод.",
  promoPlaceholder: "Например, WELCOME26",
  promoHelp: "Промокоды публикуются в нашем новостном канале и у партнёров — каждый код один раз пополняет ваш баланс.",
};

export const dashboardCopy: Record<Language, DashboardCopy> = { en, ru };
