import type { Language } from "@/components/i18n-provider";

const en = {
  navStart: "Start", navOverview: "Overview", navDevelopers: "Developers", navKeys: "API keys", navDocs: "Docs",
  navBilling: "Billing", navTopUp: "Credits",
  navGrowth: "Growth", navPromos: "Promo codes",
  navActivity: "Activity", navUsage: "Usage",
  navAccount: "Account", navProfile: "Profile", navSecurity: "Security",
  navSupportGroup: "Help", navSupport: "Support",
  supportEyebrow: "Help", supportTitle: "Support", supportSubtitle: "Chat with our AI assistant on Telegram — a human operator joins the same chat when your case needs one.",
  keysHelpTitle: "Stuck connecting your key?", keysHelpText: "Our AI support walks you through wiring it into your tool or SDK.", keysHelpCta: "Get help",
  loading: "Loading your account…", loadError: "Unable to load your account", loginPrompt: "Please log in to open your dashboard.",
  login: "Log in", logout: "Log out", closeMenu: "Close menu", menu: "Menu", topUp: "Top up", retry: "Retry",
  creditsLabel: "Credits", openProfile: "Open profile",
  manageKeys: "Manage API keys", getKey: "Get an API key", apiKey: "API key", used: "Used",
  balanceAfterDiscount: "Balance charged after discount", activeKeys: "API access", copy: "Copy", copied: "Copied",
  platformBalance: "Available credit", availableOnPlatform: "Available to spend on apiToken.sale", officialApiValue: "Equivalent Claude API usage",
  balanceValueAtDiscount: "At your current {discount}% discount, this balance covers approximately this much usage at official Anthropic API prices.",
  worthApproximately: "Worth", inClaudeApiUsage: "in Claude API usage",
  payPerOfficialDollar: "You pay ${rate} for every $1 of usage at Anthropic list prices.",
  apiAccess: "API access", usableKey: "Usable API key", usableKeys: "Usable API keys",
  checking: "Checking", statusUnavailable: "Unavailable", needsAttention: "Needs attention", ready: "Ready", setupRequired: "Setup required",
  checkingKeyStatus: "Checking your API keys…",
  keysReady: "Your API access is ready.", noKeysOverview: "Create one key to start making requests.",
  keysNeedAttention: "Your existing keys are revoked, expired, or at their spending limit.", engineNotReady: "Your API account is not ready yet. Retry shortly or contact support if this persists.", keysUnavailable: "Key status is temporarily unavailable.",
  apiAccessBlocked: "API access needs attention", keysNeedAttentionTitle: "Review your API keys",
  balanceEmptyTitle: "Your balance is empty", balanceEmptyText: "Top up before making your next API request.",
  balanceLowTitle: "Your balance is running low", balanceLowText: "Add credit now to avoid interrupted API requests.",
  keysDataLoading: "Loading API keys…", ledgerDataLoading: "Loading recent ledger history…", usageDataLoading: "Loading the 30-day usage summary…",
  keysDataUnavailable: "API keys could not be loaded. Other dashboard sections remain available.", ledgerDataUnavailable: "Ledger history could not be loaded. Balance and account data remain available.", usageDataUnavailable: "Detailed 30-day usage could not be loaded. Recent ledger details may still be available.",
  chargeEventsThisMonth: "Charge events: {count}", viewUsage: "View usage",
  officialValue30d: "Official list-price value (30d)",
  currentPricing: "Current pricing", businessAgreement: "Business agreement", discount: "off",
  negotiatedRate: "Your negotiated rate is active across every supported model.", monthlyTierProgress: "Tier progress",
  thisMonth: "Tier top-ups", platformSpend: "cumulative total", nextMilestone: "Next milestone", spendMore: "Top up {amount} more",
  unlockTier: "Unlock {tier} · {discount}% discount", milestonesComplete: "Milestones complete",
  highestTierReached: "Highest tier reached", startingTier: "Starting tier", atSpend: "At {amount} spend",
  tierStarter: "Starter", tierBuilder: "Builder", tierPro: "Pro", tierStudio: "Studio", tierScale: "Scale",
  keysEyebrow: "Developers", keysTitle: "API keys", keysSubtitle: "Create, monitor, and secure keys for every Claude integration.",
  apiEndpoint: "API endpoint", anthropicCompatible: "Anthropic-compatible", shownOnce: "Shown once",
  agentDockEyebrow: "Quick setup", agentDockTitle: "Connect Claude Code", agentDockText: "Configure Claude Code for this terminal and future terminals. No project file changes.",
  agentDockTerminal: "Persistent terminal setup", agentDockCopyTerminal: "Copy setup commands", agentDockCopyTemplate: "Copy setup template", agentDockTerminalCopied: "Setup copied", agentDockDocs: "Open full docs",
  agentDockStepOne: "Create key", agentDockStepTwo: "Copy commands", agentDockStepThree: "Run Claude",
  agentDockAgentTitle: "Using a coding agent?", agentDockAgentText: "Give it the complete integration brief instead.", agentDockCopy: "Copy agent brief", agentDockCopyWithKey: "Copy brief + key", agentDockCopied: "Brief copied",
  agentDockKeyIncluded: "Key ready", agentDockKeyPlaceholder: "Setup template", agentDockSecretNote: "The setup stores your secret in a private user environment file for future terminals. Use only on a trusted computer.", agentDockTemplateNote: "Create a key to replace YOUR_SK_POOL_API_KEY and save it for future terminals.",
  copyNewKeyNow: "Your new API key is ready", rawSecretWarning: "Copy it as many times as you need during this dashboard session. After you dismiss this panel, leave the dashboard, or refresh, the raw key cannot be shown again.",
  savedKey: "Done", openInDocs: "Open in docs →", docsShort: "Docs ↗", universalKeys: "Universal keys", optionalLabel: "Optional label", newKey: "New key",
  noKeys: "No API keys yet.", unlabelledKey: "Unlabelled key", created: "created", spent: "spent", revoke: "Revoke",
  revokeConfirm: "Revoke this API key? This cannot be undone.", createKeyError: "Unable to create the key", revokeKeyError: "Unable to revoke the key",
  quickStart: "Quick start", creditsEyebrow: "Billing", creditsTitle: "Top up balance", creditsSubtitle: "Enter the whole USD amount you want to add to your API balance.",
  currentBalance: "Current balance", available: "Available", reserved: "Reserved", inFlight: "In-flight requests",
  cryptoCheckout: "Crypto checkout", anyWholeAmount: "Top up any whole USD amount",
  checkoutHelp: "No preset amounts and no decimals. Pick a payment method below; the provider shows the final amount to pay.",
  creating: "Creating…", continuePayment: "Continue to payment", createCheckoutError: "Unable to create checkout",
  checkoutPending: "Checkout {id} is {status}. Refresh later to obtain its payment URL.",
  youReceive: "You receive", inClaudeApi: "of Claude API usage", officialPricing: "official Anthropic prices",
  valueOfBalance: "≈ {value} in Claude API", quickAmounts: "Quick amounts",
  perDollar: "Every $1 you pay is worth {mult} of Claude API at official Anthropic prices.",
  nextTierNudge: "Reach {tier} (−{discount}%) and {amount} becomes ≈ {value}.", valueMultiplier: "value",
  enterAmount: "Enter an amount to see what you get.",
  currentTier: "Current tier",
  topupUnlocks: "Reach {tier} (−{discount}%) by spending this within the calendar month — usage is then charged at −{discount}%",
  topupUpsell: "Spend {amount}+ this month → {tier} (−{discount}%), usage charged at that rate",
  atTier: "at {tier} −{discount}%",
  noTierYet: "No tier yet", noDiscountYet: "official prices · no discount yet",
  topupReach: "Reach {tier} (−{discount}%) with this top-up. Keep it by spending ≥ {hold} every 30 days.",
  topupNoTier: "Top up ≥ {amount} to reach {tier} (−{discount}%)",
  topupNext: "Top up {amount}+ total → {tier} (−{discount}%)",
  perDollarNone: "Below $100 there is no discount — you pay official Anthropic prices.",
  tierGetHold: "Top up {get} · keep {hold}/30d",
  keepTier: "Keep this tier", baseTierKept: "Yours by default", freeForever: "no top-up, no expiry",
  daysLeftOk: "held · {days} days left in window", daysLeftWarn: "{days} days left — spend more to keep it",
  tierBaseHint: "Default · always yours",
  tierExplainer: "Starter −60% is included. Larger cumulative top-ups unlock deeper discounts. Keep an upgraded tier by using at least 50% of its threshold every 30 days; otherwise you move down one tier.",
  howTiersWork: "How tiers work",
  standardPricing: "Standard pricing", pricingTerms: "Pricing terms", fixedRate: "Fixed rate", fixedRateSummary: "Your negotiated rate stays active without tier milestones.",
  highestTierSummary: "You have unlocked the deepest available discount.",
  remainingToUnlock: "{amount} remaining to unlock", tierProgressLabel: "Progress toward the next pricing tier",
  topupsTowardTier: "Top-ups counted toward tier: {current} of {target}",
  usageLast30Days: "Usage · 30 days", loadingUsageSummary: "Loading your recent usage…",
  usageSummaryUnavailable: "The 30-day usage summary is temporarily unavailable.",
  usageChargedAndRequests: "{charged} charged · {requests} requests",
  startFirstRequest: "Make your first API request", startFirstRequestText: "Your account is ready. Complete these three steps to connect a Claude-compatible tool.",
  createFirstKey: "Create a key", createFirstKeyHint: "Issue a secure API credential",
  connectYourTool: "Connect your tool", connectYourToolHint: "Add the endpoint and key",
  makeFirstRequest: "Make a request", makeFirstRequestHint: "Confirm the integration works",
  recentActivity: "Recent activity", latestAccountActivity: "Latest account activity", viewAllActivity: "View all activity",
  loadingRecentActivity: "Loading recent activity…", recentActivityUnavailable: "Recent activity is temporarily unavailable.",
  apiUsageActivity: "API usage", accountAdjustment: "Account adjustment",
  topupHistory: "Top-up history", histPaid: "Paid", histDiscount: "Discount", histApiValue: "API received",
  noTopups: "No top-ups yet.",
  usageEyebrow: "Activity", usageTitle: "Usage", usageSubtitle: "Exact settled usage for one rolling 30-day window, valued at Anthropic list prices.",
  sessionSavingTitle: "Save tokens by working in long sessions.", sessionSavingText: "Long sessions can take advantage of prompt caching, reducing repeated-context cost.",
  apiRouting: "API routing", availableBalance: "Available balance", totalCharged: "total balance charged after discount",
  sameBalance: "The same balance covers all Claude models exposed by the core gateway.", apiHealth: "API health",
  analyticsPending: "Analytics pending", healthPending: "Request-level health will appear when the backend exposes authoritative metrics.",
  successRate: "Success rate", averageLatency: "Avg latency", requests: "Requests", officialSpend: "Official list-price value",
  perRequestPending: "Per-request metric pending", balanceCharged: "Balance charged", afterDiscount: "After discount",
  charged30d: "Credits charged (30d)", settledCredits: "Settled after the rate active at each event", listPriceEquivalent: "List-price equivalent, not an Anthropic invoice", currentValue: "current value",
  activeDiscount: "Active discount", businessRate: "Business rate", currentB2cTier: "Current B2C tier",
  partnerRate: "Partner rate", partnerRateKicker: "Your pricing", partnerRateLabel: "Your rate",
  partnerYouPay: "You pay", partnerYouPayHint: "per $1 of official list price",
  partnerExample: "For example", partnerExampleHint: "in Claude API value per $100 topped up",
  partnerFixed: "Fixed rate", partnerFixedValue: "Always on", partnerFixedHint: "applies to every model and all usage",
  partnerExplainer: "This is a fixed partner rate — it never changes with volume and has no monthly retention target. Top up any amount; every dollar converts at this discount.",
  usageAnalytics: "Usage analytics", chartsPending: "Charts and model-level breakdowns will appear when the backend exposes authoritative request metrics.",
  comingSoon: "Coming soon", usageTrend: "Usage trend", officialSpendOverTime: "Official API spend over time",
  modelBreakdown: "Model breakdown", spendByModel: "Spend grouped by Claude model", transactions: "Recent transactions",
  time: "Time", type: "Type", reference: "Reference", amount: "Amount", noLedger: "No ledger activity yet.",
  topupType: "Top-up", adjustType: "Adjustment", billedEventOne: "{n} billed event", billedEventsFew: "{n} billed events", apiRequestsN: "{n} billed events", moreRows: "+{n} more billed events",
  claudeApiReceived: "Claude API received", atOfficialPrices: "at official Anthropic prices",
  receivedFromCharged: "from {charged} charged · {mult} value", receivedEmpty: "No usage yet — make your first call",
  dailyBurn: "Daily burn", avgPerActiveDay: "avg per active day",
  usageOverTime: "Settled usage over time", last30Official: "Rolling 30 days · official list-price value",
  chartWindowLabel: "Rolling 30 days · UTC day buckets", chartTotal: "Total", otherModels: "Other", shareOfUse: "Share of spend",
  chartDayLabel: "{date}: {value} at official list prices", tableScrollHint: "Swipe or scroll horizontally to see every column.",
  periodSummary: "30-day summary", chargeEvents: "Charge events", billedEvents: "Billed events", peakDay: "Peak UTC day",
  dailyAverage: "Daily average", noChargesPeriod: "No billed usage in the rolling 30-day window.",
  usageByKey: "Usage by API key", usageByKeySub: "Exact settled usage grouped by the key that made each billed request.",
  keysCount: "Keys", visibleCharges: "Visible charges", valueColumn: "Value", officialValueCol: "List-price value", chargedCol: "Charged", systemCharge: "System",
  tokensAndModels: "Tokens & models", tokensAndModelsSub: "Token counts and exact stored list-price value, by Claude model.",
  tokensPending: "Per-model token usage appears once your requests are metered by the engine.",
  inputTokens: "Input tokens", outputTokens: "Output tokens", cacheTokens: "Cache tokens", webSearchLabel: "Web search",
  cacheReadLabel: "Cache read", cacheWriteLabel: "Cache write", legacyUnattributed: "Legacy / unattributed", historicalUsage: "Historical value",
  bucketAttributionNote: "This value predates detailed token-bucket attribution. It is shown separately so bucket values reconcile exactly to the official total.",
  model: "Model", inputShort: "Input", outputShort: "Output", cacheShort: "Cache", cacheRdShort: "Cache rd", cacheWrShort: "Cache wr",
  profileTitle: "Profile", profileSubtitle: "Verified account details from the commercial backend.", email: "Email",
  displayName: "Display name", userId: "User ID", supportId: "Keep this ID handy when asking support to inspect API usage or billing events.",
  verified: "verified", pending: "pending", save: "Save", saving: "Saving…", profileSaved: "Saved", profileSaveError: "Unable to save your display name",
  telegram: "Telegram", notConnected: "Not connected", telegramHelp: "Connect Telegram to receive balance and usage updates.",
  connectTelegram: "Connect Telegram", botLanguage: "Bot language", english: "English", russian: "Русский",
  lowBalanceAlerts: "Low balance alerts", paymentNotifications: "Payment notifications", weeklyDigest: "Weekly usage digest",
  lowBalanceThreshold: "Low balance threshold, USD", securityHelp: "Review account access and available security controls.",
  securityTitle: "Security", securitySubtitle: "Your session is stored in a Secure, HttpOnly backend cookie.",
  twoFactorHelp: "Use Google Authenticator, Authy, 1Password or any TOTP client when two-factor authentication becomes available.",
  twoFactorTitle: "Two-factor authentication", twoFactorOn: "On", twoFactorOff: "Off",
  twoFactorGateHelp: "Protect API-key creation and guardrail changes with a code from your authenticator app. This does not add a second step to dashboard sign-in.",
  twoFactorRecoveryHelp: "No self-service recovery codes are issued yet. Keep the manual setup key in a secure password manager; contact support if you lose access to your authenticator.",
  twoFactorScan: "Scan with Google Authenticator (or any TOTP app), then enter the 6-digit code.",
  twoFactorManual: "Or enter the key manually", twoFactorVerify: "Verify & enable", twoFactorDisable: "Disable 2FA",
  twoFactorDisableHelp: "Enter a current code to turn off 2FA.",
  twoFactorError: "Couldn't start 2FA setup. Please try again.", twoFactorCodeInvalid: "Invalid or expired code. Try again.",
  twoFactorCodeRequired: "Enter your 6-digit 2FA code to issue a key.",
  twoFactorCodePlaceholder: "2FA code", twoFactorCodeLabel: "6-digit 2FA code", cancel: "Cancel",
  enable2fa: "Enable 2FA", backendRequired: "Backend support required", password: "Password", currentPassword: "Current password",
  newPassword: "New password", updatePassword: "Update password", passwordPending: "Password changes are not connected yet",
  oauthAccess: "Social sign-in", oauthAccessText: "This account signs in through Google or GitHub. It has no password stored on apiToken.sale.",
  activeSessions: "Active sessions", thisDevice: "This device", activeNow: "Active now", logoutSession: "Log out this session",
  promoEyebrow: "Rewards", promoTitle: "Promo codes",
  promoSubtitle: "Enter a promo code to add balance to your account.", activate: "Activate",
  promoPending: "", myActivations: "My activations", code: "Code", reward: "Reward",
  date: "Date", promoCredit: "Promo credit", noPromos: "No promo-code activations are visible in your recent ledger.",
  promoInput: "Promo code", promoAdded: "Added to your balance:", promoInvalid: "Enter a valid promo code.",
} as const;

export type DashboardCopy = { [K in keyof typeof en]: string };

const ru: DashboardCopy = {
  navStart: "Начало", navOverview: "Обзор", navDevelopers: "Разработчикам", navKeys: "API-ключи", navDocs: "Документация",
  navBilling: "Оплата", navTopUp: "Баланс",
  navGrowth: "Развитие", navPromos: "Промокоды",
  navActivity: "Активность", navUsage: "Использование",
  navAccount: "Аккаунт", navProfile: "Профиль", navSecurity: "Безопасность",
  navSupportGroup: "Помощь", navSupport: "Поддержка",
  supportEyebrow: "Помощь", supportTitle: "Поддержка", supportSubtitle: "Пишите нашему ИИ-ассистенту в Telegram — живой оператор подключается в тот же чат, когда вопрос требует человека.",
  keysHelpTitle: "Не выходит подключить ключ?", keysHelpText: "ИИ-поддержка проведёт по интеграции в ваш инструмент или SDK.", keysHelpCta: "Помощь",
  loading: "Загружаем аккаунт…", loadError: "Не удалось загрузить аккаунт", loginPrompt: "Войдите, чтобы открыть личный кабинет.",
  login: "Войти", logout: "Выйти", closeMenu: "Закрыть меню", menu: "Меню", topUp: "Пополнить", retry: "Повторить",
  creditsLabel: "Баланс", openProfile: "Открыть профиль",
  manageKeys: "Управлять ключами", getKey: "Получить API-ключ", apiKey: "API-ключ", used: "Использовано",
  balanceAfterDiscount: "Списано с баланса после скидки", activeKeys: "Доступ к API", copy: "Копировать", copied: "Скопировано",
  platformBalance: "Доступный баланс", availableOnPlatform: "Доступно для использования на apiToken.sale", officialApiValue: "Эквивалент использования Claude API",
  balanceValueAtDiscount: "С вашей текущей скидкой {discount}% этот баланс покрывает примерно такой объём использования по официальным ценам Anthropic API.",
  worthApproximately: "Это примерно", inClaudeApiUsage: "использования Claude API",
  payPerOfficialDollar: "Вы платите ${rate} за каждый $1 использования по официальной цене Anthropic.",
  apiAccess: "Доступ к API", usableKey: "Рабочий API-ключ", usableKeys: "Рабочие API-ключи",
  checking: "Проверяем", statusUnavailable: "Недоступно", needsAttention: "Нужно внимание", ready: "Готово", setupRequired: "Нужна настройка",
  checkingKeyStatus: "Проверяем состояние API-ключей…",
  keysReady: "Доступ к API готов.", noKeysOverview: "Создайте один ключ, чтобы начать отправлять запросы.",
  keysNeedAttention: "Существующие ключи отозваны, истекли или исчерпали лимит расходов.", engineNotReady: "API-аккаунт ещё не готов. Повторите попытку позже или обратитесь в поддержку.", keysUnavailable: "Статус ключей временно недоступен.",
  apiAccessBlocked: "Проверьте доступ к API", keysNeedAttentionTitle: "Проверьте API-ключи",
  balanceEmptyTitle: "Баланс закончился", balanceEmptyText: "Пополните его перед следующим API-запросом.",
  balanceLowTitle: "Баланс почти закончился", balanceLowText: "Пополните его сейчас, чтобы API-запросы не прервались.",
  keysDataLoading: "Загружаем API-ключи…", ledgerDataLoading: "Загружаем недавнюю историю операций…", usageDataLoading: "Загружаем сводку использования за 30 дней…",
  keysDataUnavailable: "Не удалось загрузить API-ключи. Остальные разделы кабинета доступны.", ledgerDataUnavailable: "Не удалось загрузить историю операций. Баланс и данные аккаунта доступны.", usageDataUnavailable: "Не удалось загрузить подробную статистику за 30 дней. Недавние данные журнала могут оставаться доступными.",
  chargeEventsThisMonth: "Списаний зафиксировано: {count}", viewUsage: "Открыть использование",
  officialValue30d: "Ценность по листовой цене (30 дн.)",
  currentPricing: "Текущая цена", businessAgreement: "Индивидуальные условия", discount: "скидка",
  negotiatedRate: "Согласованная ставка действует для всех поддерживаемых моделей.", monthlyTierProgress: "Прогресс тарифа",
  thisMonth: "Пополнения для тира", platformSpend: "учтено накопительно", nextMilestone: "Следующий уровень", spendMore: "Пополни ещё на {amount}",
  unlockTier: "Откроется {tier} · скидка {discount}%", milestonesComplete: "Все уровни пройдены",
  highestTierReached: "Достигнут максимальный уровень", startingTier: "Начальный уровень", atSpend: "При расходе {amount}",
  tierStarter: "Старт", tierBuilder: "Разработчик", tierPro: "Профи", tierStudio: "Студия", tierScale: "Масштаб",
  keysEyebrow: "Разработчикам", keysTitle: "API-ключи", keysSubtitle: "Создавайте, отслеживайте и защищайте ключи для интеграций с Claude.",
  apiEndpoint: "Адрес API", anthropicCompatible: "Совместим с Anthropic", shownOnce: "Показывается один раз",
  agentDockEyebrow: "Быстрая настройка", agentDockTitle: "Подключить Claude Code", agentDockText: "Настройте Claude Code для текущего и новых терминалов. Файлы проекта не меняются.",
  agentDockTerminal: "Постоянная настройка терминала", agentDockCopyTerminal: "Скопировать настройку", agentDockCopyTemplate: "Скопировать шаблон", agentDockTerminalCopied: "Настройка скопирована", agentDockDocs: "Открыть документацию",
  agentDockStepOne: "Создать ключ", agentDockStepTwo: "Скопировать команды", agentDockStepThree: "Запустить Claude",
  agentDockAgentTitle: "Работаете с ИИ-агентом?", agentDockAgentText: "Передайте ему готовое техническое задание.", agentDockCopy: "Скопировать задание", agentDockCopyWithKey: "Задание с ключом", agentDockCopied: "Задание скопировано",
  agentDockKeyIncluded: "Ключ готов", agentDockKeyPlaceholder: "Шаблон настройки", agentDockSecretNote: "Настройка сохранит секрет в закрытом пользовательском файле окружения для новых терминалов. Используйте её только на доверенном компьютере.", agentDockTemplateNote: "Создайте ключ — YOUR_SK_POOL_API_KEY заменится и сохранится для новых терминалов.",
  copyNewKeyNow: "Новый API-ключ готов", rawSecretWarning: "Копируйте его столько раз, сколько нужно в этой сессии кабинета. После закрытия панели, выхода из кабинета или обновления страницы исходный ключ нельзя будет показать снова.",
  savedKey: "Готово", openInDocs: "Открыть в документации →", docsShort: "Документация ↗", universalKeys: "Универсальные ключи", optionalLabel: "Необязательное название", newKey: "Новый ключ",
  noKeys: "API-ключей пока нет.", unlabelledKey: "Ключ без названия", created: "создан", spent: "израсходовано", revoke: "Отозвать",
  revokeConfirm: "Отозвать этот API-ключ? Действие нельзя отменить.", createKeyError: "Не удалось создать ключ", revokeKeyError: "Не удалось отозвать ключ",
  quickStart: "Быстрый старт", creditsEyebrow: "Оплата", creditsTitle: "Пополнение баланса", creditsSubtitle: "Введите целую сумму в долларах, которую хотите добавить на баланс API.",
  currentBalance: "Текущий баланс", available: "Доступно", reserved: "Зарезервировано", inFlight: "Активные запросы",
  cryptoCheckout: "Оплата криптовалютой", anyWholeAmount: "Пополнить на любую целую сумму",
  checkoutHelp: "Нет фиксированных пакетов и дробных сумм. Выберите способ оплаты ниже — сервис покажет итоговую сумму к оплате.",
  creating: "Создаём…", continuePayment: "Перейти к оплате", createCheckoutError: "Не удалось создать платёж",
  checkoutPending: "Платёж {id} имеет статус {status}. Обновите страницу позже, чтобы получить ссылку на оплату.",
  youReceive: "Вы получаете", inClaudeApi: "использования Claude API", officialPricing: "по официальным ценам Anthropic",
  valueOfBalance: "≈ {value} в Claude API", quickAmounts: "Быстрый выбор",
  perDollar: "Каждый $1 оплаты = {mult} использования Claude API по официальным ценам Anthropic.",
  nextTierNudge: "Дойдите до {tier} (−{discount}%) — и {amount} превратятся в ≈ {value}.", valueMultiplier: "ценность",
  enterAmount: "Введите сумму, чтобы увидеть, что получите.",
  currentTier: "Текущий тариф",
  topupUnlocks: "Достигнешь тарифа {tier} (−{discount}%), потратив столько за календарный месяц — и списания пойдут по −{discount}%",
  topupUpsell: "Потрать {amount}+ за месяц → {tier} (−{discount}%), списания по этой ставке",
  atTier: "по тарифу {tier} −{discount}%",
  noTierYet: "Тарифа пока нет", noDiscountYet: "офиц. цены · скидки пока нет",
  topupReach: "Пополнение даёт тариф {tier} (−{discount}%). Удерживай, тратя ≥ {hold} каждые 30 дней.",
  topupNoTier: "Пополни ≥ {amount}, чтобы получить {tier} (−{discount}%)",
  topupNext: "Пополни в сумме {amount}+ → {tier} (−{discount}%)",
  perDollarNone: "Ниже $100 скидки нет — платишь по официальным ценам Anthropic.",
  tierGetHold: "Пополнить {get} · держать {hold}/30д",
  keepTier: "Удержать тир", baseTierKept: "Есть по умолчанию", freeForever: "без пополнения, без срока",
  daysLeftOk: "удержан · осталось {days} дн.", daysLeftWarn: "осталось {days} дн. — трать больше, чтобы удержать",
  tierBaseHint: "Базовый · всегда твой",
  tierExplainer: "Старт −60% включён. Более крупные накопительные пополнения открывают дополнительные скидки. Чтобы удерживать повышенный тир, используйте не менее 50% его порога каждые 30 дней; иначе тир снизится на один уровень.",
  howTiersWork: "Как работают тарифы",
  standardPricing: "Стандартная цена", pricingTerms: "Условия цены", fixedRate: "Фиксированная ставка", fixedRateSummary: "Согласованная ставка действует без переходов между тарифами.",
  highestTierSummary: "Вы открыли максимальную доступную скидку.",
  remainingToUnlock: "Осталось пополнить на {amount}", tierProgressLabel: "Прогресс до следующего тарифа",
  topupsTowardTier: "Пополнения для тира: {current} из {target}",
  usageLast30Days: "Использование · 30 дней", loadingUsageSummary: "Загружаем недавнее использование…",
  usageSummaryUnavailable: "Сводка за 30 дней временно недоступна.",
  usageChargedAndRequests: "Списано {charged} · запросов: {requests}",
  startFirstRequest: "Отправьте первый API-запрос", startFirstRequestText: "Аккаунт готов. Выполните три шага, чтобы подключить совместимый с Claude инструмент.",
  createFirstKey: "Создайте ключ", createFirstKeyHint: "Выпустите защищённый API-ключ",
  connectYourTool: "Подключите инструмент", connectYourToolHint: "Добавьте адрес API и ключ",
  makeFirstRequest: "Отправьте запрос", makeFirstRequestHint: "Убедитесь, что интеграция работает",
  recentActivity: "Недавняя активность", latestAccountActivity: "Последние операции", viewAllActivity: "Вся активность",
  loadingRecentActivity: "Загружаем последние операции…", recentActivityUnavailable: "Последние операции временно недоступны.",
  apiUsageActivity: "Использование API", accountAdjustment: "Корректировка аккаунта",
  topupHistory: "История пополнений", histPaid: "Оплачено", histDiscount: "Скидка", histApiValue: "Получено API",
  noTopups: "Пополнений пока нет.",
  usageEyebrow: "Активность", usageTitle: "Использование", usageSubtitle: "Точные закрытые начисления за единое скользящее окно 30 дней, оценённые по листовым ценам Anthropic.",
  sessionSavingTitle: "Экономьте токены в длинных сессиях.", sessionSavingText: "Кэширование промпта сокращает стоимость повторяющегося контекста в длинных сессиях.",
  apiRouting: "Маршрутизация API", availableBalance: "Доступный баланс", totalCharged: "всего списано с учётом скидки",
  sameBalance: "Единый баланс покрывает все модели Claude, доступные через основной шлюз.", apiHealth: "Состояние API",
  analyticsPending: "Аналитика готовится", healthPending: "Метрики запросов появятся после подключения подтверждённой аналитики бэкенда.",
  successRate: "Успешность", averageLatency: "Средняя задержка", requests: "Запросы", officialSpend: "Ценность по официальной листовой цене",
  perRequestPending: "Метрика по запросам готовится", balanceCharged: "Списано с баланса", afterDiscount: "После скидки",
  charged30d: "Списано кредитов (30 дн.)", settledCredits: "Закрыто по ставке каждого события", listPriceEquivalent: "Эквивалент листовой цены, не счёт Anthropic", currentValue: "текущая ценность",
  activeDiscount: "Активная скидка", businessRate: "Корпоративная ставка", currentB2cTier: "Текущий уровень B2C",
  partnerRate: "Партнёрская ставка", partnerRateKicker: "Ваша цена", partnerRateLabel: "Ваша ставка",
  partnerYouPay: "Вы платите", partnerYouPayHint: "за $1 официальной листовой цены",
  partnerExample: "Например", partnerExampleHint: "в ценности Claude API за каждые пополненные $100",
  partnerFixed: "Фиксированная ставка", partnerFixedValue: "Всегда активна", partnerFixedHint: "действует для всех моделей и любого расхода",
  partnerExplainer: "Это фиксированная партнёрская ставка — она не меняется с объёмом и не требует удержания за месяц. Пополняйте на любую сумму: каждый доллар конвертируется по этой скидке.",
  usageAnalytics: "Аналитика использования", chartsPending: "Графики и разбивка по моделям появятся после подключения подтверждённых метрик бэкенда.",
  comingSoon: "Скоро", usageTrend: "Динамика использования", officialSpendOverTime: "Расход по официальным ценам во времени",
  modelBreakdown: "Разбивка по моделям", spendByModel: "Расход по каждой модели Claude", transactions: "Недавние операции",
  time: "Время", type: "Тип", reference: "Ссылка", amount: "Сумма", noLedger: "Операций пока нет.",
  topupType: "Пополнение", adjustType: "Коррекция", billedEventOne: "{n} тарифицированное событие", billedEventsFew: "{n} тарифицированных события", apiRequestsN: "{n} тарифицированных событий", moreRows: "+{n} тарифицированных событий",
  claudeApiReceived: "Получено Claude API", atOfficialPrices: "по официальным ценам Anthropic",
  receivedFromCharged: "из {charged} списанных · {mult} ценности", receivedEmpty: "Пока нет расхода — сделайте первый запрос",
  dailyBurn: "Расход в день", avgPerActiveDay: "в среднем за активный день",
  usageOverTime: "Закрытое использование по времени", last30Official: "Скользящие 30 дней · ценность по листовой цене",
  chartWindowLabel: "Скользящие 30 дней · дни по UTC", chartTotal: "Итого", otherModels: "Прочее", shareOfUse: "Доля расхода",
  chartDayLabel: "{date}: {value} по официальной листовой цене", tableScrollHint: "Проведите пальцем или прокрутите горизонтально, чтобы увидеть все столбцы.",
  periodSummary: "Сводка за 30 дней", chargeEvents: "Списания", billedEvents: "Тарифицированные события", peakDay: "Пиковый день UTC",
  dailyAverage: "Среднее в день", noChargesPeriod: "В скользящем 30-дневном окне нет тарифицированного использования.",
  usageByKey: "Использование по ключам", usageByKeySub: "Точные закрытые начисления, сгруппированные по ключу каждого тарифицированного запроса.",
  keysCount: "Ключей", visibleCharges: "Видимых списаний", valueColumn: "Ценность", officialValueCol: "По листовой цене", chargedCol: "Списано", systemCharge: "Система",
  tokensAndModels: "Токены и модели", tokensAndModelsSub: "Число токенов и точная сохранённая ценность по листовым ценам, по моделям Claude.",
  tokensPending: "Разбивка токенов по моделям появится, когда движок начнёт учитывать запросы.",
  inputTokens: "Входные токены", outputTokens: "Выходные токены", cacheTokens: "Кэш-токены", webSearchLabel: "Веб-поиск",
  cacheReadLabel: "Кэш чтение", cacheWriteLabel: "Кэш запись", legacyUnattributed: "Старое / без атрибуции", historicalUsage: "Историческая ценность",
  bucketAttributionNote: "Эта ценность появилась до подробного учёта по типам токенов. Она показана отдельно, чтобы сумма категорий точно совпадала с общим итогом.",
  model: "Модель", inputShort: "Вход", outputShort: "Выход", cacheShort: "Кэш", cacheRdShort: "Кэш чт", cacheWrShort: "Кэш зп",
  profileTitle: "Профиль", profileSubtitle: "Подтверждённые данные аккаунта из коммерческого бэкенда.", email: "Email",
  displayName: "Имя", userId: "ID пользователя", supportId: "Сохраните этот ID: он поможет поддержке найти данные по использованию API или оплате.",
  verified: "подтверждён", pending: "ожидает подтверждения", save: "Сохранить", saving: "Сохраняем…", profileSaved: "Сохранено", profileSaveError: "Не удалось сохранить имя",
  telegram: "Telegram", notConnected: "Не подключён", telegramHelp: "Подключите Telegram для уведомлений о балансе и использовании.",
  connectTelegram: "Подключить Telegram", botLanguage: "Язык бота", english: "English", russian: "Русский",
  lowBalanceAlerts: "Низкий баланс", paymentNotifications: "Уведомления об оплате", weeklyDigest: "Еженедельный отчёт",
  lowBalanceThreshold: "Порог низкого баланса, USD", securityHelp: "Проверьте доступ к аккаунту и доступные настройки безопасности.",
  securityTitle: "Безопасность", securitySubtitle: "Сессия хранится в защищённой HttpOnly cookie бэкенда.",
  twoFactorHelp: "Используйте Google Authenticator, Authy, 1Password или другой TOTP-клиент, когда двухфакторная защита станет доступна.",
  twoFactorTitle: "Двухфакторная аутентификация", twoFactorOn: "Вкл", twoFactorOff: "Выкл",
  twoFactorGateHelp: "Защитите создание API-ключей и изменение ограничений кодом из приложения-аутентификатора. Это не добавляет второй шаг ко входу в кабинет.",
  twoFactorRecoveryHelp: "Коды восстановления пока не выдаются. Сохраните ключ ручной настройки в защищённом менеджере паролей; если потеряете доступ к приложению, обратитесь в поддержку.",
  twoFactorScan: "Отсканируйте в Google Authenticator (или другом TOTP-приложении) и введите 6-значный код.",
  twoFactorManual: "Или введите ключ вручную", twoFactorVerify: "Проверить и включить", twoFactorDisable: "Отключить 2FA",
  twoFactorDisableHelp: "Введите текущий код, чтобы отключить 2FA.",
  twoFactorError: "Не удалось начать настройку 2FA. Попробуйте ещё раз.", twoFactorCodeInvalid: "Неверный или просроченный код. Попробуйте снова.",
  twoFactorCodeRequired: "Введите 6-значный код 2FA для выпуска ключа.",
  twoFactorCodePlaceholder: "Код 2FA", twoFactorCodeLabel: "6-значный код 2FA", cancel: "Отмена",
  enable2fa: "Включить 2FA", backendRequired: "Требуется поддержка бэкенда", password: "Пароль", currentPassword: "Текущий пароль",
  newPassword: "Новый пароль", updatePassword: "Обновить пароль", passwordPending: "Смена пароля пока не подключена",
  oauthAccess: "Вход через соцсеть", oauthAccessText: "Этот аккаунт входит через Google или GitHub. Пароль на apiToken.sale не хранится.",
  activeSessions: "Активные сессии", thisDevice: "Это устройство", activeNow: "Активно сейчас", logoutSession: "Завершить эту сессию",
  promoEyebrow: "Награды", promoTitle: "Промокоды",
  promoSubtitle: "Введите промокод, чтобы пополнить баланс.", activate: "Активировать",
  promoPending: "", myActivations: "Мои активации", code: "Код", reward: "Награда",
  date: "Дата", promoCredit: "Промо-начисление", noPromos: "В недавней истории нет активаций промокодов.",
  promoInput: "Промокод", promoAdded: "Начислено на баланс:", promoInvalid: "Введите корректный промокод.",
};

export const dashboardCopy: Record<Language, DashboardCopy> = { en, ru };
