import Link from "next/link";
import { Brand } from "@/components/ui";

export default function Landing() {
  return (
    <>
      <header className="landing-header">
        <div className="landing-header-inner">
          <Link href="/" className="brand" aria-label="APIToken Partners home">
            <Brand />
          </Link>
          <nav className="landing-nav">
            <Link href="/login" className="btn btn-ghost btn-sm">
              Sign in
            </Link>
            <Link href="/register" className="btn btn-primary btn-sm">
              Become a partner
            </Link>
          </nav>
        </div>
      </header>

      <main className="landing-main">
        {/* Hero */}
        <section className="hero">
          <span className="hero-eyebrow">Partner program · Recurring revenue share</span>
          <h1>
            Earn a share of <em>every dollar</em> your referrals spend on Claude API
          </h1>
          <p className="hero-sub">
            Bring developers and teams to apitoken.sale. Every time they top up and
            spend, you earn a commission — for as long as they stay. No caps, no
            one-time bounties.
          </p>
          <div className="hero-ctas">
            <Link href="/register" className="btn btn-primary btn-lg">
              Get your partner link
            </Link>
            <Link href="/login" className="btn btn-ghost btn-lg">
              Partner sign in
            </Link>
          </div>
          <p className="hero-note">
            Free to join · Payouts in USDT or to card · Real-time earnings dashboard
          </p>
        </section>

        {/* How it works */}
        <section className="section" id="how">
          <h2 className="section-title">How it works</h2>
          <p className="section-sub">
            Three steps between you and a recurring revenue stream.
          </p>
          <div className="steps">
            <div className="card step">
              <div className="step-num">1</div>
              <h3>Get your link</h3>
              <p>
                Register and receive a personal referral link and code. Share it in
                your community, content, or client work.
              </p>
            </div>
            <div className="card step">
              <div className="step-num">2</div>
              <h3>Users top up &amp; spend</h3>
              <p>
                People who sign up through your link are attributed to you
                permanently. They top up their balance and spend it on Claude API.
              </p>
            </div>
            <div className="card step">
              <div className="step-num">3</div>
              <h3>You earn a percentage</h3>
              <p>
                A share of everything they spend lands in your partner balance —
                tracked live, paid out on request.
              </p>
            </div>
          </div>
        </section>

        {/* Multi-level */}
        <section className="section" id="multilevel">
          <div className="split">
            <div>
              <h2>Build a team, earn on two levels</h2>
              <p>
                The program is multi-level. Beyond your direct referrals, you can
                recruit <strong>sub-partners</strong> — other people who promote the
                service under you.
              </p>
              <p>
                You earn an <strong>override percentage</strong> on the spend
                generated by your sub-partners&apos; referrals, on top of your own
                direct commission. Their earnings are never reduced — the override
                comes from the program, not from them.
              </p>
              <p>
                Invite sub-partners with one click from your dashboard: generate an
                invite link, send it, done.
              </p>
            </div>
            <div className="tier-diagram" aria-hidden>
              <div className="tier-row tier-you">
                <div>
                  <div className="tier-label">You</div>
                  <div className="tier-desc">Direct commission on your referrals</div>
                </div>
                <div className="tier-pct">your %</div>
              </div>
              <div className="tier-arrow">↓ you invite</div>
              <div className="tier-row">
                <div>
                  <div className="tier-label">Your sub-partners</div>
                  <div className="tier-desc">They earn their own commission</div>
                </div>
                <div className="tier-pct">their %</div>
              </div>
              <div className="tier-arrow">↓ their referrals spend</div>
              <div className="tier-row">
                <div>
                  <div className="tier-label">Your override</div>
                  <div className="tier-desc">Extra % on team-generated spend</div>
                </div>
                <div className="tier-pct">+ override %</div>
              </div>
            </div>
          </div>
        </section>

        {/* Commission terms */}
        <section className="section" id="terms">
          <h2 className="section-title">Individual commission terms</h2>
          <p className="section-sub">
            There is no one-size-fits-all rate. Your commission and override
            percentages are set individually by the program based on your audience,
            volume, and track record — and they can grow with your results. Your
            exact terms are always visible in your dashboard.
          </p>
        </section>

        {/* FAQ */}
        <section className="section" id="faq">
          <h2 className="section-title">FAQ</h2>
          <p className="section-sub">Common questions from new partners.</p>
          <div className="faq">
            <details>
              <summary>What exactly do I earn on?</summary>
              <p>
                On real spend. When a user you referred spends their balance on
                Claude API through apitoken.sale, a percentage of that spend is
                credited to you. Top-ups that are never spent don&apos;t generate
                commission — actual usage does.
              </p>
            </details>
            <details>
              <summary>How long is a referral attributed to me?</summary>
              <p>
                Permanently. A user who registers through your link stays your
                referral for the lifetime of their account, and you keep earning on
                everything they spend.
              </p>
            </details>
            <details>
              <summary>How and when do I get paid?</summary>
              <p>
                Request a payout from your dashboard whenever you have an available
                balance. We support USDT (TRC-20), card, and other methods by
                arrangement. Requests are reviewed and processed by the program team.
              </p>
            </details>
            <details>
              <summary>What is a sub-partner?</summary>
              <p>
                A partner you personally invited into the program. They get their own
                referral link and commission, and you earn an additional override
                percentage on the spend their referrals generate.
              </p>
            </details>
            <details>
              <summary>Does it cost anything to join?</summary>
              <p>
                No. Joining is free, and there are no volume requirements to keep
                your account. You only need an email address.
              </p>
            </details>
          </div>
        </section>

        {/* CTA */}
        <section className="section">
          <div className="cta-panel">
            <h2>Start earning today</h2>
            <p>
              Create your partner account, grab your link, and turn your audience
              into recurring revenue.
            </p>
            <Link href="/register" className="btn btn-primary btn-lg">
              Become a partner
            </Link>
          </div>
        </section>
      </main>

      <footer className="landing-footer">
        <div className="landing-footer-inner">
          <span>© {new Date().getFullYear()} APIToken Partners</span>
          <span>
            Main service:{" "}
            <a href="https://apitoken.sale" rel="noopener">
              apitoken.sale
            </a>
          </span>
        </div>
      </footer>
    </>
  );
}
